"use strict";
// Native UI and reader against previously fetched public bytes. All new package,
// confirmation, acquisition and index writes stay in memory; no network or models.
module.exports=async function(app,fixtureRoot,readerApiPath,keepOpen=false){
 const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{setTimeout}=require("node:timers"),f=require("./jats-fixtures.cjs"),{memory}=require("./fulltext-fixtures.cjs");
 // Prebuild src/reader/jats-document.ts with esbuild under Node. Obsidian's
 // renderer cannot start esbuild's worker_threads; never compile inside it.
 delete require.cache[require.resolve(readerApiPath)];const readerApi=require(readerApiPath);
 const plugin=app.plugins.plugins["research-agent-reader"],previous=plugin.getAcquisitionService();await previous.ready();
 if(plugin.isActionRunning("paper-ingest")||plugin.acquisitionDialogs.size)throw new Error("Finish intake and close confirmation dialogs before QA");
 const snapshot=JSON.parse(fs.readFileSync(path.join(fixtureRoot,"snapshot.json"),"utf8")),cache=f.storage(),content=new Map();
 for(const file of snapshot.artifact.files){const bytes=fs.readFileSync(path.join(fixtureRoot,file.path));cache.files.set(file.path,bytes);content.set(file.ref,bytes);}
 const deny=async()=>{throw new Error("Native JATS QA must not use the network or models");},provider=new previous.backend.jats.constructor({metadata:deny,download:deny},cache);
 snapshot.validation=provider.project(content.get("article.xml"),snapshot.identity,snapshot.artifact,content).validation;
 const acqStorage=memory(),job={schemaVersion:1,id:snapshot.jobId,attemptId:snapshot.attemptId,revision:1,mode:"production",deviceId:previous.deviceId,request:{input:snapshot.input,goal:"jats",includeFigures:true,versionPolicy:"record_only"},phase:"acquired",createdAt:snapshot.createdAt,updatedAt:snapshot.createdAt,detail:"Native JATS fixture",error:"",candidates:[snapshot.candidate],selectedId:snapshot.candidateId,snapshotId:snapshot.id,identity:snapshot.identity,identityCheck:"verified"};
 acqStorage.jobs.set(job.id,job);acqStorage.snapshots.set(snapshot.id,snapshot);
 const acquisition=new previous.constructor(new previous.repository.constructor(acqStorage,"production"),previous.deviceId,{mode:"production",resolve:deny,discover:deny,download:deny,verify:deny,readJatsSnapshot:s=>provider.read(s)});await acquisition.ready();
 const originalSource=plugin.getJatsIntakeService(),catalog=new (plugin.getSourceCatalog().constructor)(f.storage()),journal=f.storage(),index=f.index();
 const deps={...originalSource.deps,catalog,journal,index,read:id=>acquisition.previewJats(id),link:(id,key)=>acquisition.linkSourcePackage(id,key)};let source=new originalSource.constructor(deps);
 const old={catalog:plugin.getSourceCatalog,profiles:plugin.getVerifiedProviderProfiles,activate:plugin.activateMineruReaderView,active:app.workspace.activeLeaf,settings:JSON.stringify(plugin.settings)},checks=[];let acqModal,leaf;
 const check=(value,label)=>{assert.ok(value,label);checks.push(label);},wait=async(fn,label)=>{for(let i=0;i<600;i++){if(fn())return;await new Promise(r=>setTimeout(r,50));}throw new Error("Timeout: "+label);};
 const dialog=()=>[...plugin.acquisitionDialogs].find(m=>m.modalEl.matches(".rar-jats-save-modal")),open=async()=>{acqModal.contentEl.querySelector('[data-fulltext-action="save-jats"]').click();await wait(()=>dialog(),"JATS save dialog");return dialog();};
 try{
  plugin.acquisitionServices.set("production",acquisition);plugin.jatsIntakeService=source;plugin.getSourceCatalog=()=>catalog;plugin.getVerifiedProviderProfiles=()=>[];
  plugin.activateMineruReaderView=async articlePath=>{leaf=app.workspace.getLeaf("tab");await leaf.setViewState({type:"agent-dashboard-mineru-reader",active:true,state:{}});leaf.view.loader.load=()=>readerApi.loadJatsDocument(catalog.storage,articlePath.split("/")[1]);await leaf.view.setArticlePath(articlePath);await app.workspace.revealLeaf(leaf);};
  plugin.openFulltextAcquisition("production",job.id);acqModal=[...plugin.acquisitionModals].find(m=>m.service===acquisition);await wait(()=>acqModal.contentEl.querySelector('[data-fulltext-action="save-jats"]'),"JATS action");
  check(!acqModal.contentEl.querySelector('[data-fulltext-action="intake"]'),"JATS does not offer unsupported model/Wiki intake");check(!!acqModal.contentEl.querySelector('[data-fulltext-action="refresh-jats"]'),"JATS exposes explicit retry with a new acquisition");
  const format=acqModal.contentEl.querySelector('[aria-label="全文获取内容"]'),images=acqModal.contentEl.querySelector('.rar-jats-partial');check(getComputedStyle(images).display==="none","PDF default hides JATS image choice");format.value="jats";format.dispatchEvent(new Event("change"));check(getComputedStyle(images).display!=="none","JATS reveals same-version image choice");
  let modal=await open(),button=modal.contentEl.querySelector('[data-jats-action="save"]');check(modal.contentEl.textContent.includes(snapshot.identity.identifiers.doi),"confirmation displays exact main-article identity");check(modal.contentEl.querySelector("pre").textContent.includes("article-meta"),"raw XML evidence is passive text");check(catalog.storage.writes.length+journal.writes.length===0,"prepare and preview are read-only");
  check(button.disabled,"partial source needs explicit acceptance");for(const width of [360,680]){modal.modalEl.style.width=width+"px";await new Promise(r=>setTimeout(r,40));check(modal.contentEl.scrollWidth<=modal.contentEl.clientWidth+2,"JATS confirmation fits width "+width);}
  modal.close();check(catalog.storage.writes.length===0,"closing confirmation leaves no official package");modal=await open();button=modal.contentEl.querySelector('[data-jats-action="save"]');const accept=modal.contentEl.querySelector('[data-jats-action="accept-partial"]');accept.checked=true;accept.dispatchEvent(new Event("change"));check(!button.disabled,"acceptance enables save without model configuration");
  index.fail=true;const save=button.onclick();await button.onclick();await save;check(modal.contentEl.textContent.includes("登记待完成"),"index failure is separate from completed source publication");
  const marker=catalog.storage.writes.find(p=>p.endsWith("/_source/manifest.json")),manifest=JSON.parse(catalog.storage.files.get(marker));check(catalog.storage.writes.at(-1)===marker,"commit manifest is written last");check(catalog.storage.writes.filter(p=>p.endsWith("/article.md")).length===1,"double click creates one projection");check(![...catalog.storage.files.keys()].some(p=>p.endsWith(".pdf")||p.includes("wiki/")),"JATS publication fabricates neither PDF nor Wiki");
  modal.close();await source.dispose();source=new originalSource.constructor(deps);plugin.jatsIntakeService=source;index.fail=false;index.text="# QA index\nExisting user text\n";modal=await open();button=modal.contentEl.querySelector('[data-jats-action="save"]');check(!button.disabled,"restart reuses confirmed package");await button.onclick();check(modal.contentEl.textContent.includes("JATS 原文已保存并登记")&&index.text.includes("Existing user text"),"registration retry preserves user text");
  modal.contentEl.querySelector('[data-jats-action="read"]').click();try{await wait(()=>leaf?.view.readerPackage&&leaf.view.contentEl.querySelectorAll("[data-jats-block]").length===leaf.view.readerPackage.document.structured.blocks.length,"structured reader");}catch(e){throw new Error(e.message+": "+leaf?.view.contentEl.textContent.slice(-1000));}modal.close();acqModal.close();
  const view=leaf.view,pkg=view.readerPackage;try{await wait(()=>[...view.contentEl.querySelectorAll("img")].some(i=>i.naturalWidth>100),"real same-version image decoding");}catch(e){throw new Error(e.message+": "+JSON.stringify({visuals:pkg.visuals.map(v=>({display:v.display,anchor:v.anchorAssetPath})),blobs:pkg.verifiedAssetBlobs.size,images:[...view.contentEl.querySelectorAll("img")].map(i=>({src:i.src,complete:i.complete,width:i.naturalWidth})),text:view.contentEl.textContent.slice(-1000)}));}
  check(pkg.sourceKind==="jats"&&!pkg.document.capabilities.hasPdf&&!pkg.document.capabilities.hasPageMap,"reader exposes truthful JATS capabilities");check(view.contentEl.querySelectorAll("[data-jats-kind=table]").length===3,"real source preserves three tables");check(view.contentEl.querySelector("[colspan]")||view.contentEl.querySelector("[rowspan]"),"complex tables retain spans");
  check(pkg.visuals.every(v=>v.pageIdx===-1),"JATS visuals do not invent PDF page coordinates");check([...view.contentEl.querySelectorAll("img")].every(i=>i.src.startsWith("blob:")),"displayed figures use verified immutable blobs");
  const nav=view.contentEl.querySelector('[aria-label="JATS 章节导航"]'),last=[...nav.options].filter(o=>o.value).at(-1);nav.value=last.value;nav.dispatchEvent(new Event("change"));check(!!view.contentEl.querySelector("#"+CSS.escape(last.value)),"chapter/table selector targets an actual source block");
  const link=view.contentEl.querySelector('a[href^="#b-"]');check(!!link,"real source cross-references are linked to stable blocks");link?.click();
  const image=[...view.contentEl.querySelectorAll("img")].find(i=>i.naturalWidth>100);image.dispatchEvent(new Event("error"));check(view.contentEl.textContent.includes("未能解码显示"),"image decode failures are visible instead of reported as readable");await view.renderReference();await wait(()=>[...view.contentEl.querySelectorAll("img")].some(i=>i.naturalWidth>100),"restored image");
  view.markdownScroller.scrollTop=0;check(JSON.stringify(plugin.settings)===old.settings,"settings remain unchanged");check(plugin.acquisitionDialogs.size===0,"all confirmation dialogs are released");
  if(keepOpen)globalThis.__jatsQa={leaf,previousLeaf:old.active};
  return {ok:true,checks,version:plugin.manifest.version,blocks:pkg.document.structured.blocks.length,images:pkg.visuals.length,realModelCalls:0,realMineruCalls:0,realNetworkCalls:0,formalWrites:"memory-only"};
 }finally{
  for(const m of [...plugin.acquisitionDialogs])m.close();acqModal?.close();if(!keepOpen||!globalThis.__jatsQa){leaf?.detach();if(old.active)await app.workspace.revealLeaf(old.active);}
  plugin.getSourceCatalog=old.catalog;plugin.getVerifiedProviderProfiles=old.profiles;plugin.activateMineruReaderView=old.activate;plugin.jatsIntakeService=originalSource;plugin.acquisitionServices.set("production",previous);await source.dispose();await acquisition.dispose();plugin.notifyTaskRuns();
 }
};
