"use strict";
const assert=require("node:assert/strict"),{createHash}=require("node:crypto");
const {loadReading}=require("./reading-test-helpers"),f=require("./fulltext-pmc-fixtures.cjs"),{waitFor}=require("./fulltext-fixtures.cjs");
const {IdentityResolver,europeIdentity,crossrefIdentity}=loadReading("fulltext/identity-resolver.ts");
const {PmcProvider,pmcCandidate,pmcVersions}=loadReading("fulltext/pmc-provider.ts");
const {validatePdf,pdfEnvelope}=loadReading("fulltext/file-validator.ts");
// Independent test bundles must share the same error constructor, as the production bundle does.
const errorMocks={"./errors":loadReading("fulltext/errors.ts")};
const {PmcAcquisitionBackend}=loadReading("fulltext/pmc-backend.ts",errorMocks);
const {AcquisitionRepository}=loadReading("fulltext/repository.ts");
const {AcquisitionService}=loadReading("fulltext/service.ts",errorMocks);
const {decodePdfSnapshot}=loadReading("fulltext/contracts.ts");
const services=[],signal=()=>new AbortController().signal;
function make(options={}){const storage=options.storage||f.store(),net=options.net||f.transport(),backend=new PmcAcquisitionBackend(net,storage,options.loader||f.pdfLoader());const service=new AcquisitionService(new AcquisitionRepository(storage,"production"),"fixture-device",backend);services.push(service);return{storage,net,backend,service};}
async function selected(run){const job=await run.service.start(f.request());await waitFor(()=>run.service.get(job.id).phase==="awaiting_selection");await run.service.choose(job.id,run.service.get(job.id).candidates[0].id);return job;}
(async()=>{
	for(const kind of ["doi","pmid","pmcid"])assert.equal(europeIdentity(f.europe,{kind,value:f.ids[kind]}).identifiers[kind],f.ids[kind]);
	assert.throws(()=>europeIdentity(f.europe,{kind:"doi",value:"10.1234/other"}),/匹配/);
	assert.throws(()=>europeIdentity({...f.europe,hitCount:6},f.request().input),/多个/);
	assert.throws(()=>europeIdentity({hitCount:2,resultList:{result:[...f.europe.resultList.result,...f.europe.resultList.result]}},f.request().input),/不唯一/);
	assert.throws(()=>crossrefIdentity({...f.crossref,message:{...f.crossref.message,DOI:"10.1234/wrong"}},f.ids.doi),/不匹配/);
	const manyAuthors={message:{...f.crossref.message,author:Array.from({length:8},(_,i)=>({name:"Author "+i}))}};assert.equal(crossrefIdentity(manyAuthors,f.ids.doi).authors.length,8);
	const miss=f.transport();miss.noCrossref=true;assert.equal((await new IdentityResolver(miss).resolve(f.request().input,signal())).warnings.length,1);
	const crossOnly=f.transport();crossOnly.noEurope=true;const crossOnlyId=await new IdentityResolver(crossOnly).resolve({kind:"doi",value:f.ids.doi},signal());assert.equal(crossOnlyId.identifiers.pmcid,undefined);
	await assert.rejects(new PmcProvider(crossOnly).discover(f.request(),crossOnlyId,signal()),/没有 PMC/);
	assert.deepEqual(pmcVersions(f.listing([2,9]),"PMC123"),["PMC123.2","PMC123.9"]);
	for(const text of [f.listing([1]).replace("false","true"),f.listing([1]).replace("PMC123.1/","PMC124.1/"),"<!DOCTYPE x [<!ENTITY test SYSTEM 'file:///x'>]>"+f.listing([1]),f.listing([1,1])])assert.throws(()=>pmcVersions(text,"PMC123"));
	const decode=(record,policy="record_only")=>pmcCandidate(record,Buffer.from(JSON.stringify(record)),"PMC123.1",f.identity,f.request(policy));
	assert.equal(decode(f.manifest()).version,"version_of_record");assert.equal(decode(f.manifest(1,{pdf_url:null})),undefined);
	assert.equal(decode(f.manifest(1,{is_manuscript:true})),undefined);assert.equal(decode(f.manifest(1,{is_manuscript:true}),"record_preferred_allow_manuscript").version,"accepted_manuscript");
	for(const record of [f.manifest(2),f.manifest(1,{doi:"10.1234/wrong"}),f.manifest(1,{pmcid:"PMC124"}),f.manifest(1,{pdf_url:"https://localhost/pdf"}),f.manifest(1,{pdf_url:`s3://pmc-oa-opendata/PMC124.1/file.pdf?md5=${f.md5}`}),f.manifest(1,{pdf_url:`s3://pmc-oa-opendata/PMC123.1/file.pdf?token=secret&md5=${f.md5}`})])assert.throws(()=>decode(record));
	const versions=f.transport();versions.manifests=[f.manifest(2,{is_manuscript:true}),f.manifest(9)];const found=await new PmcProvider(versions).discover(f.request("record_preferred_allow_manuscript"),f.identity,signal());assert.deepEqual(found.map(c=>c.version),["version_of_record","accepted_manuscript"]);
	const noPdf=f.transport();noPdf.manifests=[f.manifest(1,{pdf_url:null})];await assert.rejects(new PmcProvider(noPdf).discover(f.request(),f.identity,signal()),/没有.*PDF/);
	const changed=f.transport(),provider=new PmcProvider(changed),before=await provider.discover(f.request(),f.identity,signal());changed.manifests[0].license_code="changed";await assert.rejects(provider.refresh(before[0],f.identity,f.request(),signal()),/清单已变化/);
	assert.throws(()=>pdfEnvelope(Buffer.from("<html>login</html>")),/文件头/);assert.throws(()=>pdfEnvelope(Buffer.from("%PDF-1.7 corrupted data no trailer")),/结束/);
	assert.equal((await validatePdf(f.bytes,f.identity,signal(),f.pdfLoader())).identityCheck,"verified");
	assert.equal((await validatePdf(f.bytes,f.identity,signal(),f.pdfLoader(""))).identityCheck,"needs_confirmation");
	await assert.rejects(validatePdf(f.bytes,f.identity,signal(),f.pdfLoader("Another paper DOI: 10.1234/wrong")),/冲突/);
	await assert.rejects(validatePdf(f.bytes,f.identity,signal(),f.pdfLoader(undefined,{numPages:2049})),/页数/);
	await assert.rejects(validatePdf(f.bytes,f.identity,signal(),async()=>({getDocument(){return{promise:Promise.reject(new Error("PasswordException")),async destroy(){}};}})),/密码/);
	const success=make(),job=await selected(success);await waitFor(()=>success.service.get(job.id).phase==="acquired");
	assert.equal(success.net.downloads,1);const snapshot=[...success.storage.snapshots.values()][0];assert.equal(snapshot.mode,"production");assert.equal(snapshot.validation.identityCheck,"verified");assert.equal(snapshot.artifact.byteLength,f.bytes.length);assert.equal(snapshot.candidate.pmc.license,"CC BY");
	assert.throws(()=>decodePdfSnapshot({...snapshot,artifact:{...snapshot.artifact,filename:"../escape.pdf"}}));assert.throws(()=>decodePdfSnapshot({...snapshot,attemptId:"a-00000000-0000-0000-0000-000000000000"}));
	const calls=success.net.calls.length;for(const kind of ["doi","pmid","pmcid"]){const reused=await success.service.start({...f.request(),input:{kind,value:f.ids[kind]}});assert.equal(reused.id,job.id);}assert.equal(success.net.calls.length,calls);assert.equal(success.net.downloads,1);
	const restored=make({storage:success.storage});await restored.service.ready();assert.equal(restored.service.get(job.id).phase,"acquired");assert.equal(restored.net.calls.length,0);assert.deepEqual(Buffer.from((await restored.service.preview(job.id)).bytes),f.bytes);
	success.storage.artifacts.set(snapshot.artifact.filename,Buffer.from("tampered"));await assert.rejects(restored.service.preview(job.id),/校验失败/);assert.equal(restored.service.get(job.id).phase,"interrupted");
	const pending=make({loader:f.pdfLoader("")}),pendingJob=await selected(pending);await waitFor(()=>pending.service.get(pendingJob.id).phase==="acquired");assert.equal(pending.service.get(pendingJob.id).identityCheck,"needs_confirmation");
	const wrong=make({loader:f.pdfLoader("Wrong article DOI: 10.1234/wrong")}),wrongJob=await selected(wrong);await waitFor(()=>wrong.service.get(wrongJob.id).phase==="conflict");assert.equal(wrong.storage.snapshots.size,0);assert.equal(wrong.storage.artifacts.size,1);
	const truncated=make();truncated.net.failDownload=true;const broken=await selected(truncated);await waitFor(()=>truncated.service.get(broken.id).phase==="failed");assert.equal(truncated.storage.snapshots.size,0);assert.equal([...truncated.storage.artifacts.values()][0].length,8);
	truncated.net.failDownload=false;await truncated.service.retry(broken.id);await waitFor(()=>truncated.service.get(broken.id).phase==="awaiting_selection");await truncated.service.choose(broken.id,truncated.service.get(broken.id).candidates[0].id);await waitFor(()=>truncated.service.get(broken.id).phase==="acquired");assert.equal(truncated.storage.artifacts.size,2,"retry never overwrites partial attempt");
	const checksum=make();checksum.net.manifests[0].pdf_url=checksum.net.manifests[0].pdf_url.replace(f.md5,"0".repeat(32));const mismatched=await selected(checksum);await waitFor(()=>checksum.service.get(mismatched.id).phase==="failed");assert.equal(checksum.service.get(mismatched.id).errorCode,"checksum_mismatch");assert.equal(checksum.storage.snapshots.size,0);
	const recoveredCommit=make();recoveredCommit.storage.failJob=j=>j.phase==="acquired";const partiallySaved=await selected(recoveredCommit);await waitFor(()=>recoveredCommit.service.get(partiallySaved.id).storageWarning);assert.equal(recoveredCommit.storage.snapshots.size,1);
	recoveredCommit.storage.failJob=null;const finished=make({storage:recoveredCommit.storage});await finished.service.ready();assert.equal(finished.service.get(partiallySaved.id).phase,"acquired");assert.equal(finished.net.downloads,0);
	const cancellation=make();let late,started=false;cancellation.net.download=async(_url,sig,sink,progress)=>{started=true;await new Promise(resolve=>late=resolve);await sink.write(f.bytes);progress(f.bytes.length,f.bytes.length);};
	const cancelled=await selected(cancellation);await waitFor(()=>started);cancellation.service.stop(cancelled.id);await waitFor(()=>cancellation.service.get(cancelled.id).phase==="cancelled");late();await new Promise(r=>setTimeout(r,10));assert.equal(cancellation.storage.snapshots.size,0);
	const deadlines=new Map();let nextTimer=0;
	const TimedService=loadReading("fulltext/service.ts",{...errorMocks,"node:timers":{setTimeout(fn,ms){const id=++nextTimer;deadlines.set(id,{fn,ms});return id;},clearTimeout(id){deadlines.delete(id);}}}).AcquisitionService;
	let releaseIdentity;
	const delayedIdentity=new TimedService(new AcquisitionRepository(f.store(),"production"),"fixture-device",{mode:"production",resolve:()=>new Promise(r=>releaseIdentity=r),discover:async()=>{throw new Error("Late identity must not continue");}});services.push(delayedIdentity);
	const overdue=await delayedIdentity.start(f.request());await waitFor(()=>releaseIdentity);[...deadlines.values()].find(t=>t.ms===20000).fn();await waitFor(()=>delayedIdentity.get(overdue.id).phase==="failed");assert.equal(delayedIdentity.get(overdue.id).errorCode,"timeout");
	releaseIdentity(f.identity);await new Promise(r=>setTimeout(r,10));assert.equal(delayedIdentity.get(overdue.id).phase,"failed");
	const slowStore=f.store(),slowNet=f.transport();let releaseDownload,downloadStarted=false;
	slowNet.download=async()=>{downloadStarted=true;await new Promise(r=>releaseDownload=r);};
	const slow=new TimedService(new AcquisitionRepository(slowStore,"production"),"fixture-device",new PmcAcquisitionBackend(slowNet,slowStore,f.pdfLoader()));services.push(slow);
	const waiting=await slow.start(f.request());await waitFor(()=>slow.get(waiting.id).phase==="awaiting_selection");assert.equal(deadlines.size,0,"manual source selection has no deadline");
	await slow.choose(waiting.id,slow.get(waiting.id).candidates[0].id);await waitFor(()=>downloadStarted);[...deadlines.values()].find(t=>t.ms===180000).fn();await waitFor(()=>slow.get(waiting.id).phase==="failed");releaseDownload();await new Promise(r=>setTimeout(r,10));assert.equal(slowStore.snapshots.size,0);assert.equal(slow.get(waiting.id).errorCode,"timeout");
	console.log("PASS PMC: exact identifiers, complete authors, Crossref miss, version discovery, manuscript policy, scoped locators, no PDF, changed manifests, PDF validation, real snapshots, alias reuse, tampering, partial files, retry and cancellation");
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await Promise.all(services.map(s=>s.dispose()));});
