"use strict";
// Real services and writer, memory-only files/journals. No network, model or filesystem cleanup.
const assert=require('node:assert/strict'),{loadReading}=require('./reading-test-helpers');
const {readingFixture,topicFixture,TFile}=require('./answer-excerpt-fixtures.cjs');
const mocks={obsidian:{TFile,Modal:class{},parseYaml:()=>({}),normalizePath:p=>p}};
const {prepareAnswerExcerpt,AnswerExcerptService}=loadReading('learning/answer-excerpts.ts',mocks);
const {topicAnswerSnapshot,readAnswerSnapshot}=loadReading('learning/answer-snapshot.ts',mocks);
const {prepareAnswerExcerptCuration,answerExcerptAddition}=loadReading('curation/answer-excerpt.ts',mocks);
const {CurationService,validatedReview}=loadReading('curation/service.ts',mocks),{CurationWriter}=loadReading('curation/writer.ts',mocks);
const {curationParagraphs}=loadReading('curation/policy.ts',mocks),{chunkDocument,contentHash}=loadReading('retrieval/chunks.ts',mocks);
const {learningBlockRanges,maskLearningBlocks,literalLearningBlock}=loadReading('learning/curated-block.ts');
const {readVaultEvidencePackets}=loadReading('services/vault-evidence.ts',mocks),{LexicalVaultRetriever}=loadReading('query/lexical-retrieval.ts',mocks);
async function fixture(eol='\n',topic=false){
 const f=readingFixture(); f.app.vault.getFileByPath=p=>f.files.get(p)?.file||null;f.app.vault.cachedRead=f.app.vault.read;f.app.metadataCache={getFileCache:()=>({})};
 if(topic){const t=await topicFixture(),study=await t.study();f.service=new AnswerExcerptService(f.app,(ref,s)=>readAnswerSnapshot(t.storage,ref,s));f.answer=()=>topicAnswerSnapshot(study,study.nodes[0].id);f.topic=t;}
 let file=(await f.service.save(prepareAnswerExcerpt(f.answer(),0,undefined,'MEMOSENTINEL\n<script>bad</script>'))).file;
 file=await f.service.saveHumanRevision(file,'HUMANSENTINEL\n```dataviewjs\nwindow.danger=1\n```\n[[injected]]\n### heading');
 const target='wiki/concepts/qa-example.md',original=['---','title: Example','---','# Example','','## Evidence','EVIDENCESENTINEL keep original.','','## Links','[[wiki/methods/keep]]',''].join(eol);f.put(target,original);f.put('研究主题索引.md','# Index\n');f.put('wiki/log.md','# Log\n');f.writes.length=0;
 const records=new Map(),workspace={ready:async()=>{},repository:{get:()=>{throw Error('invented session');}},document:()=>{throw Error('original not evidence');}},store={list:async kind=>[...records.keys()].filter(k=>k.startsWith(kind+':')).map(k=>k.slice(kind.length+1)),read:async(kind,id)=>structuredClone(records.get(kind+':'+id)),write:async(kind,v)=>{records.set(kind+':'+v.id,structuredClone(v));}};
 const makeService=()=>new CurationService(f.app,workspace,store,()=>{throw Error('model forbidden');},undefined,f.service),curation=makeService(),writer=new CurationWriter(curation),paragraph=curationParagraphs(original)[0].id;
 const prepare=(roles=['ai','human','note'])=>prepareAnswerExcerptCuration(f.app,f.service,file.path,target,paragraph,roles),preview=async roles=>{const review=await curation.saveAnswerExcerpt(await prepare(roles)),plan=await writer.preview(review.id,['s-0']);return{review,plan};};
 return{...f,file,target,original,records,curation,writer,prepare,preview,makeService,paragraph};
}
let count=0;async function test(name,fn){await fn();console.log('PASS answer excerpt curation: '+name);count++;}
(async()=>{
 await test('roles explicit, local preparation read-only, durable review reuse after restart',async()=>{const f=await fixture();await assert.rejects(f.prepare([]),/角色/);await assert.rejects(f.prepare(['human','ai']),/角色/);await assert.rejects(f.prepare(['ai','ai']),/角色/);const c=await f.prepare(['human']);assert.deepEqual(f.writes,[]);assert.equal(f.records.size,0);const r=await f.curation.saveAnswerExcerpt(c);assert.equal(r.usage.calls,0);assert.equal((await f.curation.saveAnswerExcerpt(c)).id,r.id);const fresh=f.makeService();await fresh.ready();assert.equal(fresh.errors.length,0);await new CurationWriter(fresh).preview(r.id,['s-0']);await assert.rejects(f.curation.generate(c),/不调用模型/);assert.deepEqual(f.writes,[]);});
 await test('exact content roles, literal unsafe text, YAML/headings/links and CRLF preserved',async()=>{for(const eol of ['\n','\r\n']){const f=await fixture(eol),{plan}=await f.preview(['human','note']),after=plan.writes[0].after;assert.ok(after.includes('人工修订稿（基于 AI 回答）'));assert.ok(!after.includes('原始 AI 回答片段：'));assert.ok(after.includes('MEMOSENTINEL'));assert.equal(learningBlockRanges(after).length,1);assert.ok(!maskLearningBlocks(after).includes('HUMANSENTINEL'));assert.ok(after.startsWith(f.original.slice(0,f.original.indexOf('EVIDENCESENTINEL'))));assert.ok(after.includes('[[wiki/methods/keep]]'));if(eol==='\r\n')assert.ok(!/(?<!\r)\n/.test(after));await f.writer.apply(plan);assert.equal((await f.service.load(f.file.path)).digest,f.file.digest);}});
 await test('source, manual, status, target, index, log mutations block before target writes',async()=>{for(const part of ['answer','manual','status','target','index','log']){const f=await fixture(),{plan}=await f.preview();if(part==='answer'){f.node.content+='changed';f.persist();}else if(part==='manual')await f.service.saveNote(f.file,'changed');else if(part==='status')await f.service.setCompleted(f.file,true);else f.files.get(part==='target'?f.target:part==='index'?'研究主题索引.md':'wiki/log.md').text+='changed';f.writes.length=0;await assert.rejects(f.writer.apply(plan),/变化|修改|预览/);assert.deepEqual(f.writes,[]);}});
 await test('missing original answer and target paths cannot bypass checks',async()=>{const f=await fixture();for(const target of ['wiki/sources/paper.md','papers/example/article.md','wiki/qa/a.md','wiki/concepts/../x.md'])await assert.rejects(prepareAnswerExcerptCuration(f.app,f.service,f.file.path,target,f.paragraph,['ai']),/只能/);f.storage.files.clear();await assert.rejects(f.prepare(),/缺失/);assert.deepEqual(f.writes,[]);});
 await test('forged role, source, body, snapshot, citations, target and mixed adapter rejected',async()=>{const f=await fixture(),{review}=await f.preview();for(const edit of [r=>r.context.answerExcerpt.roles=['paper'],r=>r.context.answerExcerpt.snapshot.record.note='forged',r=>r.context.source.path='papers/fake.md',r=>r.context.excerpt={},r=>r.context.target.path='wiki/sources/fake.md',r=>r.suggestions[0].text='paper proven',r=>r.suggestions[0].kind='replace',r=>r.suggestions[0].citations=[{id:'P1',quote:'fake'}],r=>r.usage.calls=1,r=>r.context.sessionId='fake']){const copy=structuredClone(review);edit(copy);assert.throws(()=>validatedReview(copy));}await assert.rejects(f.curation.decide(review.id,'s-0','pending','edited'),/重新准备/);});
 await test('queued and process-boundary cancellation preserve notes and recovery',async()=>{const f=await fixture(),{plan}=await f.preview(),c=new AbortController();c.abort();await assert.rejects(f.writer.apply(plan,c.signal),/abort/i);assert.deepEqual(f.writes,[]);const process=f.app.vault.process,c2=new AbortController();f.app.vault.process=async(...args)=>{c2.abort();return process(...args);};await assert.rejects(f.writer.apply(plan,c2.signal),/abort/i);assert.deepEqual(f.writes,[]);assert.equal(f.curation.revisions.get(plan.id).state,'recovery');});
 await test('partial writes/response loss resume through a new service exactly once',async()=>{for(const responseLoss of [false,true]){const f=await fixture(),{plan}=await f.preview(),process=f.app.vault.process;f.app.vault.process=async(...args)=>{if(!responseLoss&&args[0].path==='研究主题索引.md')throw Error('disk full');await process(...args);if(responseLoss)throw Error('response lost');};await assert.rejects(f.writer.apply(plan),/disk full|response lost/);assert.equal(f.curation.revisions.get(plan.id).state,'recovery');f.app.vault.process=process;const service=f.makeService();await service.ready();await new CurationWriter(service).resume(plan.id);assert.equal(service.revisions.get(plan.id).state,'applied');assert.equal(learningBlockRanges(f.files.get(f.target).text).length,1);assert.equal(service.reviews.get(plan.reviewId).suggestions[0].decision,'applied');}});
 await test('answer changes after commit stop remaining writes, recovery stays blocked',async()=>{const f=await fixture(),{plan}=await f.preview(),process=f.app.vault.process;f.app.vault.process=async(...args)=>{await process(...args);if(args[0].path===f.target){f.node.content+=' changed';f.persist();}};await assert.rejects(f.writer.apply(plan),/变化/);assert.deepEqual(f.writes,[f.target]);await assert.rejects(f.writer.resume(plan.id),/变化/);});
 await test('duplicate application, duplicate excerpt and undo respect later user edits',async()=>{const f=await fixture(),{plan}=await f.preview();await Promise.all([f.writer.apply(plan),f.writer.apply(plan)]);assert.equal(f.writes.filter(p=>p===f.target).length,1);await assert.rejects(f.prepare(),/已有/);const after=f.files.get(f.target).text;f.files.get(f.target).text+='USER';await assert.rejects(f.writer.previewUndo(plan.id),/后续编辑/);f.files.get(f.target).text=after;await f.writer.applyUndo(await f.writer.previewUndo(plan.id));assert.equal(f.files.get(f.target).text,f.original);assert.ok(f.files.get('wiki/log.md').text.includes('撤销'));assert.equal((await f.service.load(f.file.path)).digest,f.file.digest);});
 await test('file identity swap inside process refused',async()=>{const f=await fixture(),{plan}=await f.preview(),process=f.app.vault.process;f.app.vault.process=async(file,fn)=>{f.files.get(file.path).file=new TFile(file.path);return process(file,fn);};await assert.rejects(f.writer.apply(plan),/替换/);assert.deepEqual(f.writes,[]);});
 await test('topic committed request preserved, no extra teaching and no reading repository',async()=>{const f=await fixture('\n',true),calls=f.topic.calls(),{plan}=await f.preview(['ai']);await f.writer.apply(plan);assert.equal(f.topic.calls(),calls);assert.ok(plan.writes[0].after.includes(f.file.record.answer.ref.route));assert.equal((await f.service.load(f.file.path)).digest,f.file.digest);});
 await test('saved batches become stale after excerpt changes and expose revision recheck',async()=>{const f=await fixture(),{review}=await f.preview();await f.service.saveNote(f.file,'changed');f.curation.noteChange(f.file.path);assert.ok(f.curation.changesPending);await f.curation.inspect();assert.equal(f.curation.reviews.get(review.id).state,'stale');const g=await fixture(),{plan}=await g.preview();await g.writer.apply(plan);g.node.content+='changed';g.persist();await g.curation.inspect();assert.match(g.curation.revisions.get(plan.id).needsReview,/变化/);});
 await test('formal chunks and direct fallback exclude learning block while keeping exact evidence offsets',async()=>{const f=await fixture(),{plan}=await f.preview(),text=plan.writes[0].after;f.files.get(f.target).text=text;const chunks=chunkDocument({path:f.target,title:'Example',text,hash:contentHash(text),origins:[],depth:'x-ray',basis:'paper'});assert.ok(chunks.some(c=>c.text.includes('EVIDENCESENTINEL')));assert.ok(chunks.every(c=>!c.text.includes('HUMANSENTINEL')&&!c.text.includes('MEMOSENTINEL')));assert.ok(curationParagraphs(text).every(p=>!p.text.includes('HUMANSENTINEL')));const packets=await readVaultEvidencePackets(f.app,{candidate_paths:[f.target]});assert.ok(packets[0].content.includes('EVIDENCESENTINEL'));assert.ok(!packets[0].content.includes('HUMANSENTINEL'));const start=text.indexOf('HUMANSENTINEL'),forged=await readVaultEvidencePackets(f.app,{knowledge_passages:[{path:f.target,origins:[],hash:contentHash(text),start,end:start+10,role:'evidence'}]});assert.equal(forged.length,0);const retriever=new LexicalVaultRetriever(f.app);assert.equal((await retriever.retrieve('HUMANSENTINEL',[],{allowedPrefixes:['wiki/concepts']})).candidate_paths.length,0);assert.equal((await retriever.retrieve('EVIDENCESENTINEL',[],{allowedPrefixes:['wiki/concepts']})).candidate_paths[0],f.target);});
 await test('long blocks never leak across chunk boundaries; unterminated and embedded fences',async()=>{const long=literalLearningBlock('SECRET '.repeat(2000)+'\n```\n# fake\n```'),text='# Title\n\nBefore visible.\n\n'+long+'\n\nAfter visible.';assert.equal(learningBlockRanges(text).length,1);assert.equal(maskLearningBlocks(text).length,text.length);const chunks=chunkDocument({path:'wiki/concepts/a.md',title:'A',text,hash:contentHash(text),origins:[]});assert.ok(chunks.every(c=>!c.text.includes('SECRET')&&!c.text.includes('fake')));assert.ok(chunks.some(c=>c.text.includes('After visible')));const unfinished='Before\n```rar-learning-note\nHIDDEN';assert.ok(!maskLearningBlocks(unfinished).includes('HIDDEN'));assert.equal(learningBlockRanges('```text\n```rar-learning-note\n```').length,0);});
 console.log(`ANSWER_EXCERPT_CURATION_OK (${count} groups; memory-only)`);
})().catch(e=>{console.error(e);process.exitCode=1;});
