const assert=require("node:assert/strict"),{randomUUID}=require("node:crypto"),{loadReading}=require("./reading-test-helpers"),f=require("./source-intake-fixtures.cjs");
const {SourceIntakeService}=loadReading("papers/source-intake.ts"),{SourceCatalog}=loadReading("papers/catalog.ts"),{loadPdfSource,decodeSourceManifest}=loadReading("sources/pdf-package.ts"),{validateSourceConfirmation}=loadReading("papers/confirmation.ts");
const all=[];
function setup(source=f.source(),storage=f.storage(),journal=f.storage(),index=f.index(),legacy=[]){let linked=0;const catalog=new SourceCatalog(storage,async()=>legacy),deps={deviceId:f.sha("device"),catalog,journal,index,readSource:async()=>source,render:async()=>f.raster(),link:async()=>{linked++;}},service=new SourceIntakeService(deps);all.push(service);return{source,storage,journal,index,legacy,catalog,deps,service,get linked(){return linked;}};}
const present=async r=>{const plan=await r.service.prepare(r.source.snapshot.jobId),shown=await r.service.present(plan.requestId);return{plan,shown};};
const save=async r=>{const {plan,shown}=await present(r);return r.service.save(plan.requestId,shown.digest);};
(async()=>{
try{
 const a=setup(),first=await a.service.prepare(a.source.snapshot.jobId);assert.equal(a.storage.writes.length+a.journal.writes.length,0,"prepare is read-only");
 assert.equal((await a.service.save(first.requestId,"forged")).phase,"failed");assert.equal(a.storage.writes.length+a.journal.writes.length,0);
 const display=await a.service.present(first.requestId);assert.equal(a.storage.writes.length+a.journal.writes.length,0);
 const result=await a.service.save(first.requestId,display.digest);assert.equal(result.phase,"saved",result.error);const pkg=await loadPdfSource(a.storage,result.packageKey);
 assert.equal(pkg.snapshot.identity.evidence[0].provider,"europe-pmc","Crossref is not required");assert.equal(pkg.confirmation.schemaVersion,2);assert.ok(!a.storage.files.has(`papers/${result.packageKey}/article.md`));assert.equal(a.index.writes,1);assert.equal(a.linked,1);
 assert.throws(()=>validateSourceConfirmation({...pkg.confirmation,schemaVersion:1},pkg.manifest.requestId,pkg.snapshot));assert.throws(()=>validateSourceConfirmation(pkg.confirmation,"r-"+randomUUID(),pkg.snapshot));
 assert.throws(()=>validateSourceConfirmation({...pkg.confirmation,primaryArtifactHash:"0".repeat(64)},pkg.manifest.requestId,pkg.snapshot));
 const n=a.storage.writes.length,second=await a.service.prepare(a.source.snapshot.jobId);assert.ok(second.existing);assert.equal((await a.service.save(second.requestId,"")).phase,"saved");assert.equal(a.storage.writes.length,n);assert.equal(a.index.writes,1);
 const v2=structuredClone(a.source);v2.snapshot.id="s-"+randomUUID();v2.snapshot.candidate.pmc.sourceVersionId="PMC123.2";v2.snapshot.candidate.pmc.pdfKey="PMC123.2/PMC123.2.pdf";
 const b=setup(v2,a.storage,f.storage(),a.index),different=await save(b);assert.equal(different.phase,"saved",different.error);assert.notEqual(different.packageKey,result.packageKey);assert.equal(different.paperId,result.paperId);assert.equal(different.citekey,result.citekey);
 const manuscript=structuredClone(v2);manuscript.snapshot.id="s-"+randomUUID();manuscript.snapshot.candidate.version="accepted_manuscript";const c=setup(manuscript,a.storage,f.storage(),a.index);assert.equal((await save(c)).phase,"saved");assert.equal((await a.catalog.list()).packages.length,3,"same DOI preserves different versions and manuscript types");
 const noDoi=f.source();delete noDoi.snapshot.identity.identifiers.doi;noDoi.snapshot.validation.doiCandidates=[];const d=setup(noDoi);assert.equal((await save(d)).phase,"saved","PMCID-only identity can be saved");
 const old=setup(f.source(),f.storage(),f.storage(),f.index(),[{path:"Clippings/old.md",kind:"markdown",identifiers:a.source.snapshot.identity.identifiers,title:"old",citekey:result.citekey}]);const oldPlan=await old.catalog.prepare(old.source.snapshot);assert.ok(!oldPlan.reuse&&oldPlan.warnings.length);assert.equal(oldPlan.citekey,result.citekey);
 old.legacy.push({path:"wiki/sources/other.md",kind:"wiki",identifiers:a.source.snapshot.identity.identifiers,title:"old",citekey:"other"});await assert.rejects(old.catalog.prepare(old.source.snapshot),/citekey/);
 for(const point of ["_source/validation.json","_source/identity-page.png"]){const r=setup();let failed=false;r.storage.before=async p=>{if(p.endsWith(point)&&!failed){failed=true;throw new Error("simulated disk interruption");}};const failedResult=await save(r);assert.equal(failedResult.phase,"failed");await assert.rejects(loadPdfSource(r.storage,failedResult.packageKey),/尚未提交/);r.storage.before=undefined;
  const recovered=setup(r.source,r.storage,r.journal,r.index),plan=await recovered.service.prepare(r.source.snapshot.jobId);assert.ok(plan.recovering);const shown=await recovered.service.present(plan.requestId);const done=await recovered.service.save(plan.requestId,shown.digest);assert.equal(done.phase,"saved",done.error);assert.equal(r.storage.writes.filter(p=>p.endsWith("/source.pdf")).length,1,"recovery does not recopy complete PDF");}
 const modified=setup();modified.storage.before=async p=>{if(p.endsWith("_source/validation.json"))throw new Error("stop");};const interrupted=await save(modified),pdfPath=`papers/${interrupted.packageKey}/source.pdf`;modified.storage.before=undefined;modified.storage.files.set(pdfPath,Buffer.from("user changed PDF"));const recovered=setup(modified.source,modified.storage,modified.journal,modified.index),attempt=await save(recovered);assert.equal(attempt.phase,"failed");assert.equal(modified.storage.files.get(pdfPath).toString(),"user changed PDF");
 const pending=setup();pending.index.fail=true;const committed=await save(pending);assert.equal(committed.phase,"registration_pending");await loadPdfSource(pending.storage,committed.packageKey);pending.index.fail=false;pending.index.text="# User index\n\nKeep my text\n";const repair=setup(pending.source,pending.storage,pending.journal,pending.index),repairPlan=await repair.service.prepare(pending.source.snapshot.jobId);assert.ok(repairPlan.existing);assert.equal((await repair.service.save(repairPlan.requestId,"")).phase,"saved");assert.ok(pending.index.text.includes("Keep my text"));
 const cancelled=setup();let cancelPlan;cancelled.storage.after=async p=>{if(p.endsWith("/source.pdf"))assert.ok(cancelled.service.cancel(cancelPlan.requestId));};const cp=await present(cancelled);cancelPlan=cp.plan;assert.equal((await cancelled.service.save(cp.plan.requestId,cp.shown.digest)).phase,"cancelled");assert.ok(cancelled.storage.files.has(`papers/${cp.plan.packageKey}/source.pdf`));await assert.rejects(loadPdfSource(cancelled.storage,cp.plan.packageKey));
 const gate=setup();let gp;gate.storage.before=async p=>{if(p.endsWith("_source/manifest.json"))assert.equal(gate.service.cancel(gp.requestId),false);};const shown=await present(gate);gp=shown.plan;assert.equal((await gate.service.save(gp.requestId,shown.shown.digest)).phase,"saved");
 const marker=setup();marker.storage.before=async p=>{if(p.endsWith("_source/manifest.json"))throw new Error("commit failed");};assert.equal((await save(marker)).phase,"failed","a failed commit marker is not registration-pending");
 const collision=setup();const coll=await present(collision);await collision.storage.mkdir("papers");await collision.storage.mkdir("papers/"+coll.plan.packageKey);assert.equal((await collision.service.save(coll.plan.requestId,coll.shown.digest)).phase,"failed");const retry=setup(collision.source,collision.storage,collision.journal,collision.index);const retryResult=await save(retry);assert.equal(retryResult.phase,"failed");assert.ok(retryResult.error.includes("所有权"));
 const {legacyCatalogAssociation}=loadReading("papers/agent-intake.ts");const associated=await legacyCatalogAssociation(a.catalog,{doi:a.source.snapshot.identity.identifiers.doi,duplicateStatus:"none"});assert.equal(associated.citekey,result.citekey);assert.ok(associated.notes[0].includes("none"));
 const foreign=new SourceIntakeService({...modified.deps,deviceId:f.sha("other-device")});all.push(foreign);await assert.rejects(foreign.prepare(modified.source.snapshot.jobId),/另一设备/);
 const wrong=setup();wrong.source.bytes=Buffer.from("changed PDF");await assert.rejects(wrong.service.prepare(wrong.source.snapshot.jobId),/内容与获取快照/);assert.equal(wrong.storage.writes.length,0);
 assert.throws(()=>decodeSourceManifest({...pkg.manifest,schemaVersion:99}));a.storage.files.set(`papers/${result.packageKey}/source.pdf`,Buffer.from("tampered"));await assert.rejects(loadPdfSource(a.storage,result.packageKey),/缺失|修改|limit/);await assert.rejects(a.catalog.prepare(a.source.snapshot));
 console.log("SOURCE_INTAKE_OK: no-model publication, v2 binding, independent versions, legacy relations, manifest-last commit, read-only preparation, cancellation, idempotent recovery, index repair and edit preservation");
}finally{await Promise.all(all.map(s=>s.dispose()));}
})().catch(e=>{console.error(e);process.exitCode=1;});
