"use strict";
// Real services/writer with memory-only vault and journal. No filesystem cleanup or model/network calls.
const assert=require("node:assert/strict"),path=require("node:path"),{loadReading}=require("./reading-test-helpers");
class TFile{constructor(p){this.path=p;this.basename=path.posix.basename(p,".md");this.extension="md";this.stat={size:0};}}
const obsidian={TFile,MarkdownView:class{},Notice:class{},normalizePath:p=>p,parseYaml:text=>Object.fromEntries(text.split(/\r?\n/).filter(l=>l.includes(":")).map(l=>{const i=l.indexOf(":");return[l.slice(0,i),l.slice(i+1).trim().replace(/^"|"$/g,"")];}))},mocks={obsidian};
const {AnnotationService}=loadReading("annotations/annotation-service.ts",mocks),{excerptRevision}=loadReading("annotations/excerpt.ts"),{ExcerptLibraryService}=loadReading("annotations/excerpt-library.ts",mocks);
const {prepareExcerptCuration,excerptAddition}=loadReading("curation/excerpt.ts",mocks),{CurationService,validatedReview}=loadReading("curation/service.ts",mocks),{CurationWriter}=loadReading("curation/writer.ts",mocks),{curationParagraphs}=loadReading("curation/policy.ts",mocks);
async function fixture({eol="\n",source="Clippings/excerpt.md",target="wiki/concepts/example.md",metadata="title: Example",sourceMetadata="",quote="Repeated **sentence** with 2 mg and [[link]]."}={}){
 const body=[...(sourceMetadata?["---",sourceMetadata,"---"]:[]),"# Article","",quote,"","😀 Second: "+quote,""].join(eol),start=body.lastIndexOf(quote),original=["---",metadata,"---","# Example","","## Scope","Keep existing context.","","## Links","[[wiki/methods/existing]]",""].join(eol);
 const files=new Map(),writes=[],records=new Map();const put=(p,text)=>files.set(p,{file:new TFile(p),text});put(source,body);put(target,original);put("研究主题索引.md","# Index\n");put("文献索引.md","# Papers\n");put("wiki/log.md","# Log\n");
 const app={vault:{getFileByPath:p=>files.get(p)?.file||null,getAbstractFileByPath:p=>files.get(p)?.file||null,getMarkdownFiles:()=>[...files.values()].map(v=>v.file).filter(v=>v instanceof TFile),read:async f=>files.get(f.path).text,cachedRead:async f=>files.get(f.path).text,
 createFolder:async p=>files.set(p,{file:{path:p}}),create:async(p,text)=>{assert.ok(!files.has(p));put(p,text);writes.push(p);return files.get(p).file;},process:async(f,fn)=>{const v=files.get(f.path);v.text=fn(v.text);writes.push(f.path);}},metadataCache:{getFileCache:()=>({frontmatter:{}})}};
 const record=await new AnnotationService(app,{}).createExcerpt({sourcePath:source,selectedText:quote,sourceStart:start,sourceEnd:start+quote.length,prefix:body.slice(Math.max(0,start-80),start),suffix:body.slice(start+quote.length,start+quote.length+80),sourceRevision:excerptRevision(body),section:"",context:"",isTableCell:false,anchorRect:{}},"My inference: 999 mg.\n[click](https://example.invalid) <script>code</script>");writes.length=0;
 const workspace={ready:async()=>{},repository:{get:()=>{throw Error("fictitious reading session");}},document:()=>{throw Error("fictitious reading document");}},store={list:async kind=>[...records.keys()].filter(k=>k.startsWith(kind+":" )).map(k=>k.split(":")[1]),read:async(kind,id)=>structuredClone(records.get(kind+":"+id)),write:async(kind,value)=>records.set(kind+":"+value.id,structuredClone(value))};
 const service=new CurationService(app,workspace,store,()=>{throw Error("model must not run");}),writer=new CurationWriter(service),paragraph=curationParagraphs(original)[0];
 const prepare=async(include=false)=>prepareExcerptCuration(app,record,target,paragraph.id,include),preview=async(include=false)=>{const review=await service.saveExcerpt(await prepare(include));return{review,plan:await writer.preview(review.id,["s-0"])};};
 return{files,app,writes,records,record,source,target,original,body,service,writer,workspace,store,paragraph,prepare,preview,put};
}
let count=0;async function test(name,run){await run();count++;console.log("PASS excerpt curation: "+name);}
(async()=>{
 await test("local preparation and preview never write notes or invent sessions",async()=>{const f=await fixture(),context=await f.prepare();assert.deepEqual(f.writes,[]);assert.equal(f.records.size,0);assert.equal(context.sessionId,"");assert.equal(context.evidence.length,0);const {review,plan}=await f.preview();assert.equal(review.usage.calls,0);assert.equal(plan.writes.length,3);assert.deepEqual(f.writes,[]);await assert.rejects(f.service.generate(context),/不调用模型/);assert.equal(validatedReview(review).id,review.id);});
 await test("exact quote and optional labelled notes use literal Markdown; LF/CRLF and links preserved",async()=>{for(const eol of ["\n","\r\n"]){const f=await fixture({eol}),{plan}=await f.preview(true),after=plan.writes[0].after;assert.ok(after.includes("Repeated \\*\\*sentence\\*\\*"));assert.ok(after.includes("\\[\\[link\\]\\]"));assert.ok(after.includes("个人备注（用户记录"));assert.ok(after.includes("999 mg"));assert.ok(!after.includes("<script>"));assert.ok(after.includes("[[wiki/methods/existing]]"));assert.ok(!after.includes("[[Clippings/"));if(eol==="\r\n")assert.ok(!/(?<!\r)\n/.test(after));await f.writer.apply(plan);assert.equal(f.files.get(f.source).text,f.body);assert.equal(f.writes.filter(p=>p===f.record.annotationPath).length,0);}});
 await test("source, full excerpt, target and index changes refuse before note writes",async()=>{for(const kind of ["source","excerpt","target","index"]){const f=await fixture(),{plan}=await f.preview(),p=kind==="source"?f.source:kind==="excerpt"?f.record.annotationPath:kind==="target"?f.target:"研究主题索引.md";f.files.get(p).text+="\nExternal";await assert.rejects(f.writer.apply(plan),/变化|预览|摘录/);assert.deepEqual(f.writes,[]);}});
 await test("queued cancellation and process-boundary cancellation protect notes",async()=>{const f=await fixture(),{plan}=await f.preview(),controller=new AbortController();controller.abort();await assert.rejects(f.writer.apply(plan,controller.signal),/abort/i);assert.equal(f.records.size,1);const c=new AbortController(),process=f.app.vault.process;f.app.vault.process=async(...args)=>{c.abort();return process(...args);};await assert.rejects(f.writer.apply(plan,c.signal),/abort/i);assert.deepEqual(f.writes,[]);assert.equal(f.service.revisions.get(plan.id).state,"recovery");});
 await test("partial writes and response loss recover after new service without duplicate text",async()=>{for(const loss of [false,true]){const f=await fixture(),{plan}=await f.preview(),process=f.app.vault.process;f.app.vault.process=async(...args)=>{if(!loss&&args[0].path==="研究主题索引.md")throw Error("disk unavailable");await process(...args);if(loss)throw Error("response lost");};await assert.rejects(f.writer.apply(plan),/disk unavailable|response lost/);assert.equal(f.service.revisions.get(plan.id).state,"recovery");const after=f.files.get(f.target).text;f.app.vault.process=process;const restored=new CurationService(f.app,f.workspace,f.store,()=>{throw Error("model");});await restored.ready();await new CurationWriter(restored).resume(plan.id);assert.equal(f.files.get(f.target).text,after);assert.equal(restored.revisions.get(plan.id).state,"applied");assert.equal(restored.reviews.get(plan.reviewId).suggestions[0].decision,"applied");}});
 await test("source changes after target commit stop remaining writes and preserve recovery",async()=>{const f=await fixture(),{plan}=await f.preview(),process=f.app.vault.process;f.app.vault.process=async(...args)=>{await process(...args);if(args[0].path===f.target)f.files.get(f.source).text+="source changed";};await assert.rejects(f.writer.apply(plan),/版本已变化/);assert.deepEqual(f.writes,[f.target]);await assert.rejects(f.writer.resume(plan.id),/版本已变化/);});
 await test("same preview applies once, duplicate excerpt blocks, undo respects later edits",async()=>{const f=await fixture(),{plan}=await f.preview();await Promise.all([f.writer.apply(plan),f.writer.apply(plan)]);assert.equal(f.writes.filter(p=>p===f.target).length,1);await assert.rejects(f.prepare(),/已有这条摘录/);const after=f.files.get(f.target).text;f.files.get(f.target).text+="User edit";await assert.rejects(f.writer.previewUndo(plan.id),/后续编辑/);f.files.get(f.target).text=after;const undo=await f.writer.previewUndo(plan.id);await f.writer.applyUndo(undo);assert.equal(f.files.get(f.target).text,f.original);assert.ok(f.files.get("研究主题索引.md").text.includes(f.target.slice(0,-3)));assert.ok(f.files.get("wiki/log.md").text.includes("撤销"));});
 await test("forged input, altered quote, replacement and unselected paragraphs are refused",async()=>{const f=await fixture(),{review}=await f.preview();for(const mutate of [r=>r.context.excerpt.snapshot.record.selectedText="Invented",r=>r.context.excerpt.includeManual=true,r=>r.suggestions[0].text="Invented",r=>r.suggestions[0].kind="replace",r=>r.context.sessionId="fake-session",r=>r.context.key="f".repeat(64)]){const broken=structuredClone(review);mutate(broken);assert.throws(()=>validatedReview(broken),/摘录/);}await assert.rejects(prepareExcerptCuration(f.app,f.record,f.target,"missing",false),/凭据/);await assert.rejects(f.service.decide(review.id,"s-0","pending","Edited"),/原句不能/);});
 await test("target path and paper identity boundaries do not use matching titles",async()=>{const f=await fixture({target:"wiki/sources/example.md"});await assert.rejects(f.prepare(),/剪藏/);await assert.rejects(prepareExcerptCuration(f.app,f.record,"papers/source.md","p",false),/请选择/);let p=await fixture({source:"papers/source.md",target:"wiki/sources/example.md",metadata:"title: Example\nsource_path: papers/source.md"});await p.prepare();p=await fixture({source:"papers/source.md",target:"wiki/sources/example.md",metadata:"title: Example"});await assert.rejects(p.prepare(),/无法准确匹配/);p=await fixture({source:"papers/source.md",target:"wiki/sources/example.md",metadata:"source_path: papers/source.md\nreading_depth: metadata-only"});await assert.rejects(p.prepare(),/仅有元数据/);});
 await test("packages cannot bypass loaders and nested package paths cannot become plain Markdown",async()=>{for(const p of ["papers/package/article.md","papers/package/other.md"]){const f=await fixture({source:p});await assert.rejects(f.prepare(),/桌面本地知识库|包内摘录/);assert.deepEqual(f.writes,[]);}});
 await test("note file replacement during process is refused",async()=>{const f=await fixture(),{plan}=await f.preview(),process=f.app.vault.process;f.app.vault.process=async(file,fn)=>{f.files.get(file.path).file=new TFile(file.path);return process(file,fn);};await assert.rejects(f.writer.apply(plan),/移动或替换/);assert.deepEqual(f.writes,[]);});
 await test("saved manual batches participate in stale review inspection without a reading session",async()=>{const f=await fixture(),{review}=await f.preview();f.files.get(f.source).text+="changed";await f.service.inspect();assert.equal(f.service.reviews.get(review.id).state,"stale");});
 await test("a conflicting DOI blocks an otherwise matching source path",async()=>{const f=await fixture({source:"papers/source.md",target:"wiki/sources/example.md",sourceMetadata:"doi: 10.1000/first",metadata:"title: Example\nsource_path: papers/source.md\ndoi: 10.1000/second"});await assert.rejects(f.prepare(),/无法准确匹配/);});
 await test("MinerU dispatch re-verifies the package and refuses asset validation failures",async()=>{const f=await fixture({source:"papers/package/article.md"});let opens=0,checks=0,closed=0,bad=false;f.app.vault.adapter={getBasePath:()=>"memory-vault"};const module=loadReading("curation/excerpt.ts",{...mocks,"../reading/document":{ReadingDocumentLoader:class{async open(kind,p){assert.equal(kind,"article");assert.equal(p,f.source);opens++;return{source:{kind:"article",path:p,fingerprint:"a".repeat(64),title:"package"},verify:async()=>{checks++;if(bad)throw Error("asset invalid");},destroy:async()=>{closed++;}};}}}});const c=await module.prepareExcerptCuration(f.app,f.record,f.target,f.paragraph.id,false);assert.equal(c.excerpt.sourceMode,"article");assert.equal(opens,checks);assert.equal(checks,closed);bad=true;await assert.rejects(module.verifyExcerptCuration(f.app,c,c.target.hash),/asset invalid/);assert.equal(closed,opens);assert.deepEqual(f.writes,[]);});
 await test("JATS excerpt uses the real package verifier with in-memory storage",async()=>{
  const x=await require("./jats-wiki-fixtures.cjs").fixture(),p=`papers/${x.key}/article.md`,bytes=await x.source.read(p),body=Buffer.from(bytes).toString("utf8"),quote="This synthetic abstract is long enough to exercise bounded draft tools",start=body.indexOf(quote);assert.ok(start>=0);
  const f=await fixture();f.put(p,body);f.put(p.replace("article.md","_source/manifest.json"),Buffer.from(await x.source.read(p.replace("article.md","_source/manifest.json"))).toString("utf8"));f.app.vault.adapter={getBasePath:()=>path.resolve("memory-vault")};
  const record=await new AnnotationService(f.app,{}).createExcerpt({sourcePath:p,selectedText:quote,sourceStart:start,sourceEnd:start+quote.length,prefix:body.slice(Math.max(0,start-80),start),suffix:body.slice(start+quote.length,start+quote.length+80),sourceRevision:excerptRevision(body),section:"",context:"",isTableCell:false,anchorRect:{}},"");f.writes.length=0;
  const {openStructuredDocument}=loadReading("reading/structured-document.ts"),module=loadReading("curation/excerpt.ts",{...mocks,"../reading/document":{ReadingDocumentLoader:class{async open(kind,source){assert.equal(kind,"structured");return openStructuredDocument(path.resolve("memory-vault"),source,x.source);}}}});
  const context=await module.prepareExcerptCuration(f.app,record,f.target,f.paragraph.id,false);assert.equal(context.source.kind,"structured");await module.verifyExcerptCuration(f.app,context,context.target.hash);const xml=context.source.structured.manifest.files.find(f=>f.path==="_source/article.xml"),key=`papers/${x.key}/${xml.path}`,original=await x.source.read(key);x.source.files.set(key,Buffer.from("corrupt"));await assert.rejects(module.verifyExcerptCuration(f.app,context,context.target.hash));x.source.files.set(key,original);assert.deepEqual(f.writes,[]);
 });
 console.log(`EXCERPT_CURATION_OK (${count} groups)`);
})().catch(error=>{console.error(error);process.exitCode=1;});
