const assert=require("node:assert/strict"),{loadReading}=require("./reading-test-helpers"),f=require("./jats-fixtures.cjs");
const {JatsIntakeService}=loadReading("jats/intake.ts"),{SourceCatalog}=loadReading("papers/catalog.ts"),{loadJatsSource}=loadReading("sources/jats-package.ts"),{loadJatsDocument}=loadReading("reader/jats-document.ts");
(async()=>{
 const source=f.fixture(),acquired=await source.acquire(),storage=f.storage(),journal=f.storage(),index=f.index(),catalog=new SourceCatalog(storage),deps={deviceId:f.sha("device"),catalog,journal,index,read:async()=>acquired,link:async()=>{}},s=new JatsIntakeService(deps);
 try{const p=await s.prepare(acquired.snapshot.jobId);assert.equal(storage.writes.length+journal.writes.length,0);assert.equal((await s.save(p.requestId,"forged",false)).phase,"failed");assert.equal(storage.writes.length,0);
  const saved=await s.save(p.requestId,p.evidenceDigest,false);assert.equal(saved.phase,"saved",saved.error);assert.ok(storage.writes.at(-1).endsWith("_source/manifest.json"));const pkg=await loadJatsSource(storage,p.packageKey);assert.equal(pkg.projection.projectionId,acquired.projection.projectionId);assert.ok(pkg.files.has("_source/article.xml"));assert.ok(index.text.includes(p.packageKey));
  const doc=await loadJatsDocument(storage,p.packageKey);assert.equal(doc.sourceKind,"jats");assert.equal(doc.document.capabilities.hasPageMap,false);assert.equal(doc.document.capabilities.hasPdf,false);assert.equal(doc.verifiedAssetBlobs.size,1);assert.equal(doc.visuals[0].pageIdx,-1);
  const restart=new JatsIntakeService(deps);try{const plan=await restart.prepare(acquired.snapshot.jobId);assert.ok(plan.existing);const count=storage.writes.length;assert.equal((await restart.save(plan.requestId,"",false)).phase,"saved");assert.equal(storage.writes.length,count);}finally{await restart.dispose();}
  const pdf=require("./source-intake-fixtures.cjs").source().snapshot;assert.equal((await catalog.prepare(pdf)).citekey,p.citekey,"PDF flow sees JATS canonical citekey");assert.ok(!(await catalog.prepare(pdf)).reuse,"JATS is not a PDF duplicate");
  storage.files.set(`papers/${p.packageKey}/article.md`,Buffer.from("user changed text"));await assert.rejects(loadJatsSource(storage,p.packageKey),/修改|缺失/);
 }finally{await s.dispose();}
 const partial=f.fixture();partial.transport.failImage=true;const raw=await partial.acquire();assert.equal(raw.snapshot.validation.requestSatisfaction,"partial");const st=f.storage(),j=f.storage(),ix=f.index(),d={...deps,catalog:new SourceCatalog(st),journal:j,index:ix,read:async()=>raw},service=new JatsIntakeService(d);
 try{const p=await service.prepare(raw.snapshot.jobId);assert.equal((await service.save(p.requestId,p.evidenceDigest,false)).phase,"failed");assert.equal(st.writes.length,0);ix.fail=true;const result=await service.save(p.requestId,p.evidenceDigest,true);assert.equal(result.phase,"registration_pending",result.error);ix.fail=false;ix.text="# User index\nKeep my text\n";const retry=new JatsIntakeService(d);try{const rp=await retry.prepare(raw.snapshot.jobId);assert.equal((await retry.save(rp.requestId,"",false)).phase,"saved");assert.ok(ix.text.includes("Keep my text"));}finally{await retry.dispose();}}finally{await service.dispose();}
 for(const failAt of ["article.md","_source/source-map.json","_source/manifest.json"]){const st=f.storage(),journal=f.storage(),d={...deps,catalog:new SourceCatalog(st),journal,index:f.index()},first=new JatsIntakeService(d);st.before=async path=>{if(path.endsWith("/"+failAt))throw new Error("disk interruption");};let plan;try{plan=await first.prepare(acquired.snapshot.jobId);assert.equal((await first.save(plan.requestId,plan.evidenceDigest,false)).phase,"failed");}finally{await first.dispose();}st.before=undefined;const resume=new JatsIntakeService(d);try{const rp=await resume.prepare(acquired.snapshot.jobId);assert.ok(rp.recovering);assert.equal((await resume.save(rp.requestId,rp.evidenceDigest,false)).phase,"saved");assert.equal(st.writes.filter(k=>k.endsWith("/article.md")).length,1);}finally{await resume.dispose();}}
 const corrupt=f.fixture();corrupt.transport.corruptImage=true;await assert.rejects(corrupt.acquire(),/MD5/);
 console.log("JATS_INTAKE_OK: same-version media, formal package verification, immutable projection, catalog interoperability, partial consent, index retry and restart recovery");
})().catch(e=>{console.error(e);process.exitCode=1;});
