"use strict";
// All business stores and documents live in memory. No network, disk writes, or cleanup.
const assert = require("node:assert/strict");
const { loadReading, memoryStorage } = require("./reading-test-helpers");
const { createReadingSession, addReadingNode } = loadReading("reading/session.ts");
const { ReadingRepository } = loadReading("reading/store.ts");
const { ReadingWorkspaceService } = loadReading("reading/workspace.ts");
const { ReadingAssistantService } = loadReading("assistant/service.ts");
const { resolveAssistantAction, safeAssistantExportPath } = loadReading("assistant/action-results.ts");
const { validateAssistantRun } = loadReading("assistant/store.ts");
const { contentHash } = loadReading("retrieval/chunks.ts");
(async () => {
	const session = createReadingSession({ kind: "pdf", path: "a.pdf", fingerprint: "a".repeat(64), title: "Test" });
	const parent = addReadingNode(session, null); parent.status = "done";
	const repo = new ReadingRepository(memoryStorage()); await repo.add(session);
	const workspace = { ready: async () => {}, repository: repo, document: async () => ({ source: session.source, verify: async () => {} }), generate: async (id, nodeId) => repo.transact(id, s => { s.nodes.find(n => n.id === nodeId).status = "done"; }) };
	let generated = 0, linked;
	const generate = workspace.generate; workspace.generate = (...args) => { generated++; return generate(...args); };
	await assert.rejects(ReadingWorkspaceService.prototype.advance.call(workspace, session.id, { expectedParentId: "old", prepared: async () => {} }), /起点已变化/); assert.equal(repo.get(session.id).nodes.length, 1);
	await ReadingWorkspaceService.prototype.advance.call(workspace, session.id, { expectedParentId: parent.id, prepared: async nodeId => { assert.equal(generated, 0); linked = nodeId; assert.equal(repo.get(session.id).nodes[1].id, linked); } });
	assert.equal(generated, 1);
	await assert.rejects(ReadingWorkspaceService.prototype.advance.call(workspace, session.id, { expectedParentId: linked, prepared: async () => { throw new Error("receipt disk full"); } }), /receipt disk full/);
	assert.equal(generated, 1); assert.equal(repo.get(session.id).nodes[2].status, "failed");
	const execution = { id: "attempt", state: "running", detail: "pending", updated: new Date().toISOString(), nodeId: linked };
	const action = { id: "action", kind: "advance", nodeIds: [parent.id], target: "", scope: "node", contextHash: "a".repeat(64), state: "opened", execution };
	const revisions = []; let review; let exported = "---\nreading_session: " + JSON.stringify(session.id) + "\n---\nContent";
	const deps = { review: () => review, revisions: () => revisions, readExport: async () => exported };
	assert.equal((await resolveAssistantAction(repo.get(session.id), action, deps)).state, "succeeded");
	await repo.transact(session.id, s => { s.nodes[1].status = "interrupted"; s.nodes[1].error = "stopped"; });
	assert.equal((await resolveAssistantAction(repo.get(session.id), action, deps)).state, "interrupted");
	await repo.transact(session.id, s => { s.nodes[1].status = "done"; });
	assert.equal((await resolveAssistantAction(repo.get(session.id), action, deps)).state, "succeeded");
	assert.equal((await resolveAssistantAction(repo.get(session.id), { ...action, nodeIds: ["wrong parent"] }, deps)).state, "needs-review");
	const exportAction = { ...action, kind: "export", execution: { ...execution, nodeId: undefined, path: "wiki/qa/test.md", hash: contentHash(exported) } };
	assert.equal((await resolveAssistantAction(session, exportAction, deps)).state, "succeeded");
	exported += "manual edit"; assert.equal((await resolveAssistantAction(session, exportAction, deps)).state, "needs-review");
	for (const path of ["wiki/qa/../sources/a.md", "C:/private.md", "wiki/qa/./a.md", "wiki/qa/a\\b.md"]) assert.equal(safeAssistantExportPath(path), false);
	const curation = { ...action, kind: "curation", execution: { ...execution, nodeId: undefined, reviewId: "review" } };
	review = { id: "review", state: "ready", context: { sessionId: session.id, nodeIds: [parent.id], target: { path: "wiki/sources/a.md" } }, suggestions: [{ decision: "pending" }] };
	assert.equal((await resolveAssistantAction(session, curation, deps)).state, "waiting");
	revisions.push({ id: "revision", reviewId: review.id, state: "applied" }); review.suggestions[0].decision = "applied";
	assert.equal((await resolveAssistantAction(session, curation, deps)).state, "succeeded");
	revisions.push({ id: "undo", reviewId: review.id, state: "applied", undoOf: "revision" });
	assert.match((await resolveAssistantAction(session, curation, deps)).detail, /撤销/);
	review.context.sessionId = "another session"; assert.equal((await resolveAssistantAction(session, curation, deps)).state, "needs-review");
	// Persistence, reopening and late callbacks: the old preview cannot write after a newer attempt.
	let calls = 0; const storage = memoryStorage(); let changed;
	const serviceDeps = { workspace, backend: () => ({ name: "fake", model: "fake", complete: async () => JSON.stringify({ step: ++calls % 2 ? { tool: "prepare_action", arguments: { kind: "export", nodeIds: [parent.id], target: "", scope: "node" } } : { tool: "final", arguments: { answer: "prepared", citations: [] } } }) }),
		subscribeActions: callback => { changed = callback; return () => { changed = undefined; }; }, resolveAction: async (id, action) => resolveAssistantAction(repo.get(id), action, deps) };
	const service = new ReadingAssistantService(serviceDeps, storage);
	const run = await service.start(session.id, parent.id, "fake", "export"); const id = run.actions[0].id;
	let first, second; await service.dispatch(run.id, id, a => { first = a.execution.id; }); await service.dispatch(run.id, id, a => { second = a.execution.id; });
	assert.notEqual(first, second);
	await assert.rejects(service.recordExecution(run.id, id, first, { state: "running" }), /最新预览/);
	await service.recordExecution(run.id, id, second, { state: "running", path: "wiki/qa/test.md", hash: contentHash(exported) });
	await assert.rejects(service.dispatch(run.id, id, () => { throw new Error("must not open"); }), /执行记录/);
	await service.recordExecution(run.id, id, second, { state: "succeeded", detail: "saved" });
	await service.refreshActions(); assert.equal(service.runs.get(run.id).actions[0].execution.state, "succeeded");
	exported += "changed"; changed(); await service.refreshActions(); assert.equal(service.runs.get(run.id).actions[0].execution.state, "needs-review");
	const restored = new ReadingAssistantService(serviceDeps, storage); await restored.ready(); await restored.refreshActions(); assert.equal(restored.runs.get(run.id).actions[0].execution.path, "wiki/qa/test.md");
	const corrupt = structuredClone(service.runs.get(run.id)); corrupt.actions[0].execution.state = "forged"; assert.throws(() => validateAssistantRun(corrupt), /执行记录/);
	await service.dispose(); await restored.dispose(); assert.equal(changed, undefined);
	console.log("ASSISTANT_ACTIONS_OK: business receipts, write-before-effect, failures, retries, edits, undo, old callbacks, restart");
})().catch(error => { console.error(error); process.exitCode = 1; });
