const assert = require("node:assert/strict");
const { loadReading, memoryStorage } = require("./reading-test-helpers");
const { ReadingRepository } = loadReading("reading/store.ts");
const { ReadingWorkspaceService } = loadReading("reading/workspace.ts");
const { createReadingSession, addReadingNode, addReadingBranch, completedMainContext, validateReadingSession } = loadReading("reading/session.ts");
const { acceptReadingCorrection, readingCoverage } = loadReading("reading/quality.ts");
(async () => {
	const source = { kind: "pdf", path: "old.pdf", title: "Paper", fingerprint: "a".repeat(64) };
	const session = createReadingSession(source); const original = addReadingNode(session, null); original.status = "done"; original.content = "Original explanation";
	session.mainSummary = "Old summary"; const oldBranch = addReadingBranch(session, original.id);
	const storage = memoryStorage(), repository = new ReadingRepository(storage); await repository.add(session);
	const service = Object.create(ReadingWorkspaceService.prototype); Object.assign(service, { repository, documents: new Map(), tasks: new Set() });
	service.generateHandler = async (sid, id) => repository.transact(sid, s => { const n = s.nodes.find(n => n.id === id); n.content = "Corrected explanation"; n.status = "done"; });
	const correctionId = await service.correct(session.id, original.id, "Check denominators"); await Promise.all([...service.tasks]);
	await repository.transact(session.id, s => acceptReadingCorrection(s, correctionId));
	let saved = repository.get(session.id);
	assert.equal(saved.mainIds.length, 1); assert.equal(saved.nodes[0].content, "Original explanation");
	assert.match(completedMainContext(saved), /Corrected explanation/);
	assert.equal(saved.branches.find(b => b.id === oldBranch.id).mainSnapshot, "Old summary");
	assert.equal(saved.branches.find(b => b.id === oldBranch.id).parentContext, "Original explanation");
	assert.match(addReadingBranch(structuredClone(saved), original.id).parentContext, /Corrected explanation/);
	validateReadingSession(structuredClone(saved)); const restored = new ReadingRepository(storage); await restored.load(); assert.equal(restored.get(session.id).nodes[0].acceptedCorrectionId, correctionId);
	const evidence = [{ id: "text-1", kind: "paper", path: "old.pdf", text: "fact", label: "Section" }, { id: "page-1", kind: "paper", path: "old.pdf", asset: "pdf-page", text: "figure", label: "Page" }, { id: "text-2", kind: "paper", path: "old.pdf", text: "other", label: "Other" }];
	await repository.transact(session.id, s => { s.nodes[0].evidence = [evidence[0]]; s.nodes[0].reviewedEvidence = ["text-1"]; s.nodes[0].providedEvidenceIds = ["text-1", "page-1"]; s.nodes[0].providedImageIds = ["page-1"]; });
	const coverage = readingCoverage(repository.get(session.id), evidence); assert.equal(coverage[0].reviewed, true); assert.equal(coverage[1].provided, true); assert.equal(coverage[2].provided, false);
	let fingerprint = "b".repeat(64), destroyed = 0;
	service.loader = { open: async (_kind, filename) => ({ source: { ...source, path: filename, fingerprint }, evidence: evidence.map(e => ({ ...e, path: filename })), verify: async () => {}, destroy: async () => { destroyed++; } }) };
	await assert.rejects(service.relocate(session.id, "new.pdf"), /内容不同/); assert.equal(repository.get(session.id).source.path, "old.pdf");
	fingerprint = source.fingerprint; storage.fail = true; await assert.rejects(service.relocate(session.id, "new.pdf"), /disk full/); assert.equal(repository.get(session.id).source.path, "old.pdf"); storage.fail = false;
	await service.relocate(session.id, "new.pdf"); saved = repository.get(session.id); assert.equal(saved.source.path, "new.pdf"); assert.equal(saved.nodes[0].evidence[0].path, "new.pdf"); assert.equal(saved.sourceRelocations[0].from, "old.pdf");
	await repository.transact(session.id, s => { s.nodes.at(-1).status = "running"; s.nodes[0].acceptedCorrectionId = undefined; });
	await assert.rejects(service.relocate(session.id, "third.pdf"), /正在生成/);
	assert.equal(destroyed, 3);
	console.log("READING_QUALITY_OK");
})().catch(e => { console.error(e); process.exitCode = 1; });
