const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { createReadingSession, addReadingNode, addReadingBranch } = loadReading("reading/session.ts");
const { readingTrail, revealReadingPath, searchReadingNodes, fitReadingZoom } = loadReading("reading/navigation.ts");
const { layoutReading } = loadReading("reading/layout.ts");
const s = createReadingSession({ kind: "pdf", path: "a.pdf", fingerprint: "a".repeat(64), title: "test" });
const main = addReadingNode(s, null); main.title = "Contrastive model"; main.status = "done";
const branch = addReadingBranch(s, main.id); const first = addReadingNode(s, branch.id, "why Contrastive learning?"); first.status = "done";
const anchor = addReadingNode(s, branch.id, "related question"); anchor.status = "done"; anchor.content = "正文中的独特关键词";
const child = addReadingBranch(s, anchor.id); const target = addReadingNode(s, child.id, "child question"); target.status = "done";
const hidden = addReadingNode(s, child.id, "hidden child"); hidden.status = "done";
const sibling = addReadingBranch(s, main.id); addReadingNode(s, sibling.id, "unrelated");
s.ui.collapsed = [branch.id, child.id, sibling.id];
assert.deepEqual(readingTrail(s, hidden.id).map((n) => n.id), [main.id, anchor.id, hidden.id]);
assert(!layoutReading(s).nodes.some((n) => n.id === hidden.id));
revealReadingPath(s, hidden.id);
assert.deepEqual(s.ui.collapsed, [sibling.id]);
assert(layoutReading(s).nodes.some((n) => n.id === hidden.id));
assert.equal(searchReadingNodes(s, "cOnTrAsTiVe")[0].id, main.id);
assert.equal(searchReadingNodes(s, "model contrastive").length, 1);
assert.equal(searchReadingNodes(s, "独特关键词")[0].id, anchor.id);
assert.equal(searchReadingNodes(s, "does-not-exist").length, 0);
assert.equal(searchReadingNodes(s, "  ").length, s.nodes.length);
assert.equal(fitReadingZoom(620, 480, 636, 496).zoom, 1);
assert.equal(fitReadingZoom(1000, 1000, 516, 816).zoom, 0.5);
assert.deepEqual(fitReadingZoom(1000, 9000, 516, 816), { zoom: 0.4, limited: true });
assert.deepEqual(fitReadingZoom(1000, 9000, 0, 0), { zoom: 0.4, limited: true });
console.log("READING_NAVIGATION_OK");
