const assert = require("node:assert/strict");
const { loadReading, memoryStorage } = require("./reading-test-helpers");
const { createReadingSession, addReadingNode } = loadReading("reading/session.ts");
const { ReadingRepository } = loadReading("reading/store.ts");
const { ReadingEngine, validateReadingResult } = loadReading("reading/engine.ts");
(async () => {
	const repo = new ReadingRepository(memoryStorage());
	const session = createReadingSession({ kind: "pdf", path: "a.pdf", fingerprint: "a".repeat(64), title: "paper" }); const node = addReadingNode(session, null); await repo.add(session);
	let calls = 0; const evidence = [{ id: "text-1-0", kind: "paper", path: "a.pdf", label: "Page one", text: "Direct observed evidence", page: 1 }];
	const result = { title: "问题", content: "本文研究问题。[text-1-0]", evidenceIds: ["text-1-0"], outline: ["问题", "方法"], mainSummary: "已讲问题", completed: false };
	const backend = { name: "mock", model: "test", images: false, complete: async (request) => { calls++; assert.ok(request.signal); return calls % 2 ? JSON.stringify({ ids: ["text-1-0"], query: "question", needsVisual: false }) : JSON.stringify(result); } };
	const workspace = { repository: repo, document: async () => ({ evidence, catalog: "text-1-0 Page one", verify: async () => {}, image: async () => null }) };
	const engine = new ReadingEngine(workspace, () => backend);
	await Promise.all([engine.generate(session.id, node.id), engine.generate(session.id, node.id)]);
	assert.equal(calls, 2); assert.equal(repo.get(session.id).nodes[0].status, "done"); assert.equal(repo.get(session.id).mainSummary, "已讲问题");
	assert.throws(() => validateReadingResult(JSON.stringify({ ...result, evidenceIds: ["text-missing"] }), evidence, true), /未提供/);
	const next = await repo.transact(session.id, (s) => addReadingNode(s, null));
	backend.complete = async () => "malformed";
	await assert.rejects(engine.generate(session.id, next.id)); assert.equal(repo.get(session.id).nodes[1].status, "failed"); assert.equal(repo.get(session.id).mainSummary, "已讲问题");
	backend.complete = (request) => new Promise((resolve, reject) => { request.signal.addEventListener("abort", () => reject(new Error("aborted"))); });
	const pending = engine.generate(session.id, next.id); await new Promise((resolve) => setTimeout(resolve, 10)); workspace.stopHandler(session.id, next.id);
	await assert.rejects(pending); assert.equal(repo.get(session.id).nodes[1].status, "interrupted");
	console.log("READING_ENGINE_OK");
})().catch((e) => { console.error(e); process.exitCode = 1; });
