"use strict";
const assert=require("node:assert/strict"),{EventEmitter}=require("node:events"),{Readable}=require("node:stream");
const {loadReading}=require("./reading-test-helpers");
const {HttpsSourceTransport,publicAddress,sourceUrl}=loadReading("fulltext/transport.ts");
function mock(responses,addresses=[{address:"8.8.8.8",family:4}],peer){const calls=[];return{calls,async lookup(){return addresses;},request(url,options,receive){const request=new EventEmitter();calls.push({url:new URL(url),options});let closed=false,response;request.setTimeout=()=>request;request.destroy=error=>{if(closed)return;closed=true;response?.destroy();if(error)request.emit("error",error);request.emit("close");};request.end=()=>queueMicrotask(()=>{if(options.signal.aborted){request.destroy(new Error("aborted"));return;}options.signal.addEventListener("abort",()=>request.destroy(new Error("aborted")),{once:true});const socket=new EventEmitter();socket.remoteAddress=peer||addresses[0].address;request.emit("socket",socket);socket.emit("secureConnect");if(closed)return;const item=responses.shift();if(!item){request.destroy(new Error("No fixture"));return;}response=item.stream||Readable.from(item.chunks||[Buffer.from(item.body||"{}")]);response.statusCode=item.status||200;response.headers=item.headers||{"content-type":"application/json"};response.once("close",()=>request.emit("close"));receive(response);});return request;}};}
const controller=()=>new AbortController();
(async()=>{
	for(const ip of ["0.1.2.3","10.0.0.1","127.0.0.1","100.64.0.1","169.254.1.1","172.31.1.1","192.168.1.1","192.0.0.8","192.0.2.1","192.88.99.1","198.18.0.1","198.51.100.1","203.0.113.1","224.0.0.1","255.255.255.255","::","::1","::ffff:8.8.8.8","::ffff:0808:0808","fc00::1","fe80::1","2001:db8::1","2002:0808:0808::1","3fff::1","not-ip"])assert.equal(publicAddress(ip),false,ip);
	for(const ip of ["8.8.8.8","52.216.1.1","1.1.1.1","2606:4700:4700::1111","2001:4860:4860::8888"])assert.equal(publicAddress(ip),true,ip);
	for(const url of ["http://api.crossref.org/works/x","https://localhost/","https://api.crossref.org.evil.test/","https://user:pass@api.crossref.org/","https://2130706433/","https://[::1]/","https://api.crossref.org:8443/","https://api.crossref.org/#x"])assert.throws(()=>sourceUrl(url));
	const target="https://api.crossref.org/works/test",good=mock([{body:"{\"ok\":true}",headers:{"content-length":"11"}}]),transport=new HttpsSourceTransport(good);
	assert.equal((await transport.metadata(target,controller().signal)).status,200);const options=good.calls[0].options;let selected;options.lookup("api.crossref.org",{},(_err,address,family)=>selected={address,family});assert.deepEqual(selected,{address:"8.8.8.8",family:4});assert.equal(options.servername,"api.crossref.org");assert.equal(options.agent,false);assert.equal(options.headers["Accept-Encoding"],"identity");assert.equal(options.headers.Authorization,undefined);assert.equal(options.headers.Cookie,undefined);
	for(const addresses of [[{address:"127.0.0.1",family:4}],[{address:"8.8.8.8",family:4},{address:"10.0.0.1",family:4}]]){const deps=mock([],addresses);await assert.rejects(new HttpsSourceTransport(deps).metadata(target,controller().signal),/非公网/);assert.equal(deps.calls.length,0);}
	await assert.rejects(new HttpsSourceTransport(mock([{body:"{}"}],undefined,"1.1.1.1")).metadata(target,controller().signal),/实际连接/);
	await new HttpsSourceTransport(mock([{body:"{}"}],[{address:"2606:4700:4700:0:0:0:0:1111",family:6}],"2606:4700:4700::1111")).metadata(target,controller().signal);
	const redirect=mock([{status:302,headers:{location:"/works/new"}},{body:"{}"}]);await new HttpsSourceTransport(redirect).metadata(target,controller().signal);assert.equal(redirect.calls.length,2);assert.equal(redirect.calls[1].url.pathname,"/works/new");
	await assert.rejects(new HttpsSourceTransport(mock([{status:302,headers:{location:"https://www.ebi.ac.uk/other"}}])).metadata(target,controller().signal),/其他站点/);
	await assert.rejects(new HttpsSourceTransport(mock([{status:302,headers:{location:"http://api.crossref.org/"}}])).metadata(target,controller().signal),/HTTPS/);
	const retry=mock([{status:429,headers:{"retry-after":"0"}},{body:"{}"}]);await new HttpsSourceTransport(retry).metadata(target,controller().signal);assert.equal(retry.calls.length,2);
	const deferred=mock([{status:429,headers:{"retry-after":"3600"}}]);assert.equal((await new HttpsSourceTransport(deferred).metadata(target,controller().signal)).status,429);assert.equal(deferred.calls.length,1,"do not retry earlier than the requested delay");
	await assert.rejects(new HttpsSourceTransport(mock([{headers:{"content-encoding":"gzip"}}])).metadata(target,controller().signal),/压缩/);
	await assert.rejects(new HttpsSourceTransport(mock([{headers:{"content-length":String(2*1024*1024+1)}}])).metadata(target,controller().signal),/大小/);
	await assert.rejects(new HttpsSourceTransport(mock([{chunks:[Buffer.alloc(2*1024*1024),Buffer.from("x")]}])).metadata(target,controller().signal),/实际接收/);
	await assert.rejects(new HttpsSourceTransport(mock([{body:"{}",headers:{"content-length":"9"}}])).metadata(target,controller().signal),/不完整/);
	const pdfTarget="https://pmc-oa-opendata.s3.amazonaws.com/PMC123.1/PMC123.1.pdf";let written=0;const sink={async write(bytes){written+=bytes.length;}};
	for(const fixture of [{status:403},{headers:{"content-type":"text/html"}},{headers:{"content-type":"application/pdf","content-length":String(64*1024*1024+1)}}])await assert.rejects(new HttpsSourceTransport(mock([fixture])).download(pdfTarget,controller().signal,sink,()=>{}));assert.equal(written,0);
	const chunks=[Buffer.from("%PDF-"),Buffer.from(" data")],progress=[];await new HttpsSourceTransport(mock([{chunks,headers:{"content-type":"application/pdf","content-length":"10"}}])).download(pdfTarget,controller().signal,sink,(...args)=>progress.push(args));assert.equal(written,10);assert.deepEqual(progress.at(-1),[10,10]);
	await new HttpsSourceTransport(mock([{chunks,headers:{"content-type":"binary/octet-stream","content-length":"10"}}])).download(pdfTarget,controller().signal,sink,()=>{});assert.equal(written,20,"PMC S3 binary/octet-stream is accepted before PDF byte validation");
	const aborted=controller();aborted.abort();const unopened=mock([{body:"{}"}]);await assert.rejects(new HttpsSourceTransport(unopened).metadata(target,aborted.signal));assert.equal(unopened.calls.length,0);
	const xmlTarget=pdfTarget.replace(".pdf",".xml");for(const [resource,mime]of [["xml","application/xml"],["xml","binary/octet-stream"],["media","image/jpeg"]]){const network=mock([{body:"content",headers:{"content-type":mime}}]);await new HttpsSourceTransport(network).download(xmlTarget,controller().signal,sink,()=>{},{resource});assert.ok(!network.calls[0].options.headers.Accept.includes("application/pdf"));}
	for(const [resource,mime,size]of [["xml","application/xml",8],["media","image/jpeg",16]])await assert.rejects(new HttpsSourceTransport(mock([{headers:{"content-type":mime,"content-length":String(size*1024*1024+1)}}])).download(xmlTarget,controller().signal,sink,()=>{},{resource}),/大小/);
	await assert.rejects(new HttpsSourceTransport(mock([])).download(xmlTarget,controller().signal,sink,()=>{},{resource:"xml",dynamic:true}),/固定 PMC/);
	await assert.rejects(new HttpsSourceTransport(mock([{body:"<html/>",headers:{"content-type":"text/html"}}])).download(xmlTarget,controller().signal,sink,()=>{},{resource:"xml"}));
	const oaTarget="https://publisher.example.org/paper.pdf",oaNetwork=mock([{status:302,headers:{location:"https://repository.example.org/file.pdf"}},{chunks,headers:{"content-type":"application/pdf"}}]);
	await new HttpsSourceTransport(oaNetwork).download(oaTarget,controller().signal,sink,()=>{},{dynamic:true});assert.equal(oaNetwork.calls.length,2);assert.equal(oaNetwork.calls[1].options.headers.Referer,undefined);assert.equal(oaNetwork.calls[1].options.headers.Cookie,undefined);
	for(const location of ["https://127.0.0.1/pdf","https://repository.example.org/pdf?token=secret","https://reader:password@repository.example.org/pdf"])await assert.rejects(new HttpsSourceTransport(mock([{status:302,headers:{location}}])).download(oaTarget,controller().signal,sink,()=>{},{dynamic:true}));
	let lookupCount=0;const rebind=mock([{status:302,headers:{location:"https://repository.example.org/file.pdf"}}]);rebind.lookup=async()=>[{address:++lookupCount===1?"8.8.8.8":"10.0.0.1",family:4}];await assert.rejects(new HttpsSourceTransport(rebind).download(oaTarget,controller().signal,sink,()=>{},{dynamic:true}),/非公网/);
	const budget={received:0,limit:15},budgetNet=new HttpsSourceTransport(mock([{chunks,headers:{"content-type":"application/pdf"}},{chunks,headers:{"content-type":"application/pdf"}}]));await budgetNet.download(pdfTarget,controller().signal,sink,()=>{},{budget});await assert.rejects(budgetNet.download(pdfTarget,controller().signal,sink,()=>{},{budget}),/累计/);assert.ok(budget.received>15);
	const stream=new Readable({read(){}}),midflight=controller(),network=mock([{stream,headers:{"content-type":"application/pdf"}}]);
	const inFlight=new HttpsSourceTransport(network).download(pdfTarget,midflight.signal,sink,()=>midflight.abort());setTimeout(()=>stream.push(Buffer.from("%PDF-partial")),20);await assert.rejects(inFlight);assert.ok(stream.destroyed);
	console.log("PASS source transport: URL/IP policy, DNS pinning, peer check, credential isolation, redirects, bounded retry, encoded/oversize/truncated bodies and mid-stream cancellation");
})().catch(e=>{console.error(e);process.exitCode=1;});
