const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { libraryCodeLinks, codeLinkStillPresent } = loadReading("library/code-links.ts");
const paper = (key, path, association = "identified") => ({key, association, objects:[{kind:"note",id:path}]});
const a="wiki/sources/a.md", b="wiki/sources/b.md", c="wiki/code/projects/same.md", d="wiki/code/scripts/same.md", q="wiki/qa/code.md";
const papers=[paper("a",a),paper("b",b)];
const files=[a,b,c,d,q,"wiki/qa/topic.md","wiki/methods/m.md"].map(path=>({path,codeExport:path===q}));
const graph={ [a]:{[c]:1,[d]:1,"wiki/methods/m.md":1}, [c]:{[a]:2}, [q]:{[a]:1}, "wiki/qa/topic.md":{[a]:1}, "wiki/methods/m.md":{[d]:1}, [b]:{"wiki/code/projects/missing.md":1} };
const before=JSON.stringify({papers,files,graph});
const result=libraryCodeLinks(papers,files,graph);
assert.equal(result.byPaper.a.length,4);assert.equal(result.byPaper.b.length,0);
assert.equal(result.byPaper.a.filter(r=>r.path===c).length,2);
assert.equal(result.byPaper.a.find(r=>r.path===q).kind,"code-export");
assert.equal(JSON.stringify({papers,files,graph}),before);
assert.equal(libraryCodeLinks([paper("a",a,"conflict")],files,graph).byPaper.a.length,0);
assert.equal(libraryCodeLinks(papers,files.filter(f=>f.path!==c),graph).byPaper.a.some(r=>r.path===c),false);
assert.equal(libraryCodeLinks(papers,files,undefined).issues.length,1);
assert.equal(libraryCodeLinks(papers,files,{}).byPaper.a.length,0);
assert.equal(codeLinkStillPresent(result.byPaper.a[0],result.byPaper.a),true);
assert.equal(codeLinkStillPresent({...result.byPaper.a[0],notePath:b},result.byPaper.a),false);
assert.equal(codeLinkStillPresent(result.byPaper.a[0],[]),false);
const unsafe="wiki/code/projects/../outside.md";
assert.equal(libraryCodeLinks(papers,[...files,{path:unsafe}],{[a]:{[unsafe]:1}}).byPaper.a.length,0);
const many=Object.fromEntries(Array.from({length:50001},(_,i)=>['missing-'+i,1]));
assert.match(libraryCodeLinks(papers,files,{[a]:many}).issues[0],/上限/);
console.log("LIBRARY_CODE_LINKS_OK: direct directions, exact paths, exports, missing/cache/conflict, no transitive matching, stale target and bounds");
