const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { readingAssociations, readingExportDiff } = loadReading("reading/export-review.ts");
const { createReadingSession, addReadingNode } = loadReading("reading/session.ts");
const { contentHash } = loadReading("retrieval/chunks.ts");
(async () => {
	const session = createReadingSession({ kind: "article", path: "papers/a/article.md", fingerprint: "a".repeat(64), title: "学习论文" });
	const node = addReadingNode(session, null); node.status = "done"; node.title = "空间表征"; node.content = "相关方法。";
	const path = "wiki/sources/related.md"; const hash = contentHash("真实依据");
	node.evidence = [{ id: "k1", kind: "vault", path, text: "真实依据", label: "已读论文", sourceHash: hash }];
	const app = { vault: { getFileByPath: p => p === path ? { path } : null, cachedRead: async () => "真实依据" } };
	const model = async (query, options) => { assert.equal(query, session.title + "\n" + node.title); assert(!query.includes(node.content)); assert.equal(options.identityQuery, "跨论文关联笔记"); return { warnings: [], hits: [{ path, hash, title: "duplicate" }, { path: "papers/a/article.md", title: "outside" }, { path: "wiki/methods/related.md", hash, title: "方法", heading: "原理", text: "补充说明", role: "background", origins: [path] }] }; };
	const result = await readingAssociations(app, session, "node", node.id, model, new AbortController().signal);
	assert.equal(result.candidates.length, 2); assert.equal(result.candidates[0].reason, "本次回答已读取"); assert.equal(result.candidates[1].role, "背景解释");
	const cancelled = new AbortController(); cancelled.abort(); await assert.rejects(readingAssociations(app, session, "node", node.id, model, cancelled.signal), /abort/i);
	const diff = readingExportDiff("---\ncreated: old\n---\nA\nold\nZ", "---\ncreated: new\n---\nA\nnew\nZ"); assert.equal(diff.added, 1); assert.equal(diff.removed, 1); assert(diff.lines.includes("+ new"));
	assert.equal(readingExportDiff("same", "same").added, 0);
	assert(readingExportDiff("", Array(300).fill("line").join("\n")).omitted);
	console.log("READING_EXPORT_REVIEW_OK");
})().catch(error => { console.error(error); process.exitCode = 1; });
