const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { readingCitations } = loadReading("reading/presentation.ts");
const { resolveReadingQuote } = loadReading("reading/selection.ts");
const ids = ["text-0-9", "figure-0-0"];
const source = "结果 `[证据ID: text-0-9, figure-0-0]` 支持结论。另见 [text-0-9]。";
const matches = readingCitations(source, ids);
assert.equal(matches.length, 2);
assert.deepEqual(matches[0].ids, ids);
assert.equal(source.slice(matches[0].start, matches[0].end), matches[0].raw);
assert.deepEqual(readingCitations("[证据ID: text-0-9, unknown] [unknown] [普通括注]", ids), []);
assert.deepEqual(readingCitations("[证据ID： text-0-9，figure-0-0]", ids)[0].ids, ids);
const quote = resolveReadingQuote("n1", source, "结果 [证据ID: text-0-9, figure-0-0] 支持结论。");
assert.equal(quote.text, source.slice(quote.start, quote.end));
assert.ok(quote.text.includes(matches[0].raw));
const sanitized = "结果 '[证据ID: text-0-9, figure-0-0]' 支持结论。";
const wrapped = readingCitations(sanitized, ids, source)[0];
assert.equal(wrapped.raw, "`[证据ID: text-0-9, figure-0-0]`");
assert.equal(sanitized.slice(wrapped.start, wrapped.end), "'[证据ID: text-0-9, figure-0-0]'");
assert.equal(readingCitations("'[text-0-9], [figure-0-0]'", ids, "`[text-0-9], [figure-0-0]`").length, 1);
assert.equal(readingCitations("'[text-0-9], [unknown]'", ids, "`[text-0-9], [unknown]`")[0].raw, "[text-0-9]");
assert.equal(readingCitations("'[text-0-9]'", ids)[0].raw, "[text-0-9]");
console.log("READING_PRESENTATION_OK");
