"use strict";
// No network or real credentials. Small temporary records are retained; never bulk-cleaned.
const assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), os = require("node:os");
const io = require("../scripts/reading-quality-io.cjs"), r = require("../scripts/reading-quality-runner.cjs");
const { report } = require("../scripts/report-reading-quality.cjs"), { loadReading } = require("./reading-test-helpers");
const { OpenAICompatibleProvider } = loadReading("providers/adapters.ts");
const root = fs.mkdtempSync(path.join(os.tmpdir(), "rar-quality-runner-"));
const profile = r.profileInfo({ id: "synthetic", type: "openai-compatible", baseUrl: "http://127.0.0.1:8787/v1", model: "test-model", capabilities: { vision: true }, secretId: "do-not-record" });
const bytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aAdQAAAAASUVORK5CYII=", "base64");
const image = { kind: "pdf-page", sourceFile: "test/source.pdf", sourceSha256: io.sha("pdf"), page: 1, file: "images/" + io.sha(bytes) + ".png", sha256: io.sha(bytes), bytes: bytes.length, mime: "image/png", width: 1, height: 1, transform: { test: true } };
const q = { id: "Q01", sourceId: "test", primaryFormat: "pdf", instructions: "Only cite supplied evidence. Disclose uncertainty.", prompt: "What does the figure show?", evidence: [{ id: "Q01-E1", format: "pdf", page: 1, text: "2 mg, not 2 g", sha256: io.sha("2 mg, not 2 g") }], visuals: [{ id: "Q01-V1", kind: image.kind, sourceFile: image.sourceFile, sourceSha256: image.sourceSha256, page: 1, delivery: "required_not_yet_provided" }] };
q.inputHash = io.sha(JSON.stringify(q));
const q2 = { ...q, id: "Q02", visuals: [] }; delete q2.inputHash; q2.inputHash = io.sha(JSON.stringify(q2));
const sourceRoot = path.join(root, "sources"); fs.mkdirSync(sourceRoot);
const plan = { schemaVersion: 1, baselineId: "test", baselineHash: io.sha("spec"), instructionsHash: io.sha(q.instructions), evaluationMode: "fixed-evidence-qa", sourceRoot, inputs: [q, q2], images: [image], scientificReview: "pending", runnerProtocol: "rar-quality-run-1" };
plan.planHash = io.sha(JSON.stringify(plan));
const planDirectory = path.join(root, "plan"); fs.mkdirSync(planDirectory); fs.mkdirSync(path.join(planDirectory, "images")); io.save(planDirectory, "plan.json", plan); io.save(path.join(planDirectory, "images"), path.basename(image.file), bytes, true);
let tests = 0;
async function test(name, action) { await action(); tests++; console.log("PASS " + name); }
function memoryStore() {
	const events = [], results = []; let summary;
	return { events, results, get summary() { return summary; }, prepare: input => r.prepareRequest(input, [image], () => bytes, profile), begin(input) { events.push("begin:" + input.id); }, request(id, wire) { events.push("request:" + id); return io.sha(JSON.stringify(wire)); }, response(id, text) { events.push("response:" + id); return io.sha(text); }, result(record) { events.push("result:" + record.id); results.push(record); }, finish(value) { summary = value; } };
}
const rawAnswer = (text = "2 mg [Q01-E1], [Q01-V1]", finish = "stop") => ({ model: "test-model", choices: [{ message: { content: text }, finish_reason: finish }], usage: { prompt_tokens: 21, completion_tokens: 13, total_tokens: 34, completion_tokens_details: { text_tokens: 13, reasoning_tokens: 8 } } });
function fakeExecute(raw = rawAnswer(), after) { return async (request, hooks) => { const wire = { url: profile.baseUrl + "/chat/completions", method: "POST", body: { model: request.model, messages: request.messages, max_tokens: request.maxTokens, stream: false } }; hooks.onRequest(wire); hooks.onResponse({ status: 200, text: JSON.stringify(raw) }); after?.(hooks, wire); return { text: raw.choices[0].message.content, raw }; }; }
const run = (store, execute = fakeExecute(), controller = new AbortController()) => r.runCases({ plan, inputs: plan.inputs, profile, execute, store, signal: controller.signal, mode: "simulated" });
(async () => {
	await test("frozen plan hashes and inputs", () => { assert.equal(r.loadPlan(planDirectory, plan.planHash).inputs[0].inputHash, q.inputHash); assert.throws(() => r.loadPlan(planDirectory, "0".repeat(64))); });
	await test("input tampering and reference injection rejected", () => { const bad = structuredClone(plan); bad.inputs[0].expectedPoints = ["SECRET RUBRIC"]; const { inputHash, ...input } = bad.inputs[0]; bad.inputs[0].inputHash = io.sha(JSON.stringify(input)); const { planHash, ...base } = bad; bad.planHash = io.sha(JSON.stringify(base)); const folder = path.join(root, "bad-plan"); fs.mkdirSync(folder); io.save(folder, "plan.json", bad); assert.throws(() => r.loadPlan(folder, bad.planHash), /reference leakage/); });
	await test("image bytes and provenance bound to frozen input", () => { const prepared = r.prepareRequest(q, [image], () => bytes, profile); assert.equal(prepared.visuals[0].sha256, io.sha(bytes)); assert.ok(prepared.request.messages[1].content.some(c => c.image_url?.url.endsWith(bytes.toString("base64")))); assert.ok(!JSON.stringify(prepared.request).includes("expectedPoints")); assert.throws(() => r.prepareRequest(q, [image], () => Buffer.alloc(bytes.length), profile), /changed/); assert.throws(() => r.prepareRequest(q, [], () => bytes, profile)); assert.throws(() => r.prepareRequest(q, [image], () => bytes, { ...profile, vision: false })); });
	await test("profile validation and credential exclusion", () => { assert.ok(!JSON.stringify(profile).includes("do-not-record")); for (const baseUrl of ["http://example.org", "https://key@example.org", "https://example.org?key=secret"]) assert.throws(() => r.profileInfo({ ...profile, baseUrl })); assert.throws(() => r.profileInfo({ ...profile, type: "ollama" })); assert.throws(() => r.profileInfo(profile, 10000)); });
	await test("actual provider adapter preserves wire and never records authorization", async () => { let calls = 0; const plugin = { app: { secretStorage: { getSecret: () => "synthetic-key-never-record" } }, providerHttpRequest: async options => { calls++; assert.equal(options.headers.Authorization, "Bearer synthetic-key-never-record"); assert.equal(options.timeoutMs, 120000); const raw = rawAnswer(); return { status: 200, text: JSON.stringify(raw), json: raw }; } }; plugin.createLLMProvider = selected => new OpenAICompatibleProvider(plugin, { ...selected, secretId: "fake-id", timeoutSeconds: 120 }); const store = memoryStore(), summary = await run(store, r.obsidianExecutor(plugin, profile, profile)); assert.equal(calls, 2); assert.equal(summary.answered, 2); assert.equal(summary.scientificReview, "pending"); assert.equal(summary.records[0].visuals[0].modelVisualInspection, "not_verifiable"); assert.ok(!JSON.stringify(store.results).includes("synthetic-key")); });
	await test("transport cannot silently change prompt or make second call", async () => { const altered = memoryStore(); const bad = async (request, hooks) => { hooks.onRequest({ url: profile.baseUrl + "/chat/completions", method: "POST", body: { messages: [] } }); }; assert.equal((await run(altered, bad)).recorded, 1); assert.equal(altered.results[0].dispatched, false); const repeated = memoryStore(); await run(repeated, fakeExecute(rawAnswer(), (hooks, wire) => hooks.onRequest(wire))); assert.equal(repeated.results[0].state, "failed"); assert.equal(repeated.events.filter(s => s.startsWith("request")).length, 1); });
	await test("timeouts stop remaining questions with unknown cost and no retry", async () => { let calls = 0; const store = memoryStore(); const summary = await run(store, async () => { calls++; throw Object.assign(new Error("secret echoed"), { type: "timeout" }); }); assert.equal(calls, 1); assert.deepEqual(summary.remaining, ["Q02"]); assert.equal(summary.records[0].usage.total, null); assert.ok(!JSON.stringify(summary).includes("secret echoed")); });
	await test("no answer, truncation and refusal are distinct and stop batch", async () => { for (const [text, finish, expected] of [["", "stop", "empty_answer"], ["partial", "length", "truncated"], ["", "length", "truncated"], ["refused", "content_filter", "refused"]]) { const store = memoryStore(); const summary = await run(store, fakeExecute(rawAnswer(text, finish))); assert.equal(summary.records[0].state, expected); assert.equal(summary.recorded, 1); } });
	await test("cancel before dispatch and during actual adapter transport", async () => { const aborted = new AbortController(); aborted.abort(); const empty = memoryStore(); assert.equal((await run(empty, fakeExecute(), aborted)).recorded, 0); const controller = new AbortController(); let cancellations = 0; const plugin = { app: {}, providerHttpRequest: options => new Promise((resolve, reject) => { options.registerCancel(() => { cancellations++; reject(new Error("cancel")); }); controller.abort(); }) }; plugin.createLLMProvider = () => new OpenAICompatibleProvider(plugin, { ...profile, timeoutSeconds: 120 }); const store = memoryStore(), summary = await run(store, r.obsidianExecutor(plugin, profile, profile), controller); assert.equal(cancellations, 1); assert.equal(summary.records[0].state, "cancelled"); assert.equal(summary.records[0].responseReceived, false); assert.equal(summary.records[0].visuals[0].transport, "outcome_unknown"); });
	await test("storage and image failures stop before another request", async () => { const store = memoryStore(); store.result = () => { throw new Error("disk full"); }; await assert.rejects(() => run(store), /disk full/); assert.equal(store.events.filter(e => e.startsWith("request")).length, 1); const broken = memoryStore(); broken.prepare = () => { throw new Error("image changed"); }; await assert.rejects(() => run(broken), /image changed/); assert.deepEqual(broken.events, []); });
	await test("usage missing is unknown and citation syntax is not scientific scoring", () => { assert.equal(r.usage({ prompt_tokens: 1.5, total_tokens: -1 }).input, null); assert.equal(r.usage({ prompt_tokens: 0 }).input, 0); assert.deepEqual(r.checkCitations("Q01-E1 Q99-E1 Q01-V1", q), { cited: ["Q01-E1", "Q01-V1"], unknown: ["Q99-E1"], scientificSupport: "pending_independent_review" }); });
	await test("create-only storage, path isolation, and bounded reads", () => { assert.throws(() => io.save(planDirectory, "plan.json", {})); assert.throws(() => io.privateTarget(path.join(io.ROOT, "no-output"))); assert.throws(() => io.privateTarget(path.join(planDirectory, "no-output"), [planDirectory])); const vault = path.join(root, "vault"); fs.mkdirSync(vault); fs.mkdirSync(path.join(vault, ".obsidian")); assert.throws(() => io.privateTarget(path.join(vault, "no-output"))); assert.throws(() => io.readFile(planDirectory, "../plan.json")); assert.throws(() => io.readFile(planDirectory, "plan.json", 10)); });
	await test("disk run and review retain actual wire images and reject tampering", async () => { const directory = path.join(root, "run"); fs.mkdirSync(directory); io.save(directory, "manifest.json", { protocol: "rar-quality-run-1", profile, pluginVersion: "test", questionIds: ["Q01", "Q02"], planHash: plan.planHash }); const store = r.diskStore(directory, planDirectory, plan, profile); const summary = await run(store, fakeExecute(rawAnswer("2 mg Q01-E1\n```\n# untrusted heading\n```"))); assert.equal(summary.answered, 2); const output = path.join(root, "review.md"); assert.equal(report(directory, output, planDirectory).records, 2); const review = fs.readFileSync(output, "utf8"); assert.ok(review.includes("````text")); assert.ok(review.includes("pending") || review.includes("待独立人工复核")); assert.match(review, /不能相加/); const assets = fs.readdirSync(output + "-assets"); assert.equal(assets.length, 1); assert.equal(io.sha(fs.readFileSync(path.join(output + "-assets", assets[0]))), image.sha256); assert.throws(() => report(directory, output, planDirectory), /already exists/); fs.appendFileSync(path.join(directory, "Q01", "response.txt"), "tampered"); assert.throws(() => report(directory, path.join(root, "tampered-review.md"), planDirectory), /changed/); assert.equal(fs.existsSync(path.join(root, "tampered-review.md")), false); });
	await test("review binds saved inputs and refuses source/plan destinations", () => {
		const directory = path.join(root, "incomplete"); fs.mkdirSync(directory);
		io.save(directory, "manifest.json", { protocol: "rar-quality-run-1", profile, pluginVersion: "test", questionIds: ["Q01"], planHash: plan.planHash });
		for (const base of [sourceRoot, planDirectory, directory]) assert.throws(() => report(directory, path.join(base, "refused.md"), planDirectory), /outside/);
		const output = path.join(root, "incomplete.md"); report(directory, output, planDirectory); assert.match(fs.readFileSync(output, "utf8"), /本题未开始/);
		const folder = path.join(directory, "Q01"); fs.mkdirSync(folder);
		io.save(folder, "input.json", { ...q, prompt: "changed prompt" }); io.save(folder, "result.json", { id: q.id, inputHash: q.inputHash });
		assert.throws(() => report(directory, path.join(root, "input-changed.md"), planDirectory), /differs from frozen plan/);
	});
	await test("public live observation preserves frozen baseline and pending scientific review", () => {
		const observation = require("./fixtures/reading-quality/r0-v1-model-observation.json"), spec = require("./fixtures/reading-quality/r0-v1.json");
		assert.equal(observation.baselineHash, io.sha(JSON.stringify(spec)));
		assert.equal(observation.independentReviewStatus, "pending"); assert.equal(observation.scientificPassRate, null);
		assert.equal(observation.independentlyReviewedQuestions, 0); assert.equal(observation.scientificAnswerStatus, "recorded_not_reviewed");
		const ids = spec.samples.flatMap(s => s.questions.map(q => q.id)).sort(); assert.deepEqual(observation.records.map(r => r.id).sort(), ids);
		assert.equal(observation.totals.questions, ids.length); assert.equal(new Set(observation.groups.flatMap(g => g.questions)).size, ids.length);
		assert.equal(observation.totals.imagesSubmitted, observation.records.reduce((n,r) => n + r.visuals.length, 0));
		for (const field of ["input", "output", "total", "outputText", "outputReasoning"]) {
			assert.equal(observation.totals.usage[field].reportedSum, observation.records.reduce((n,r) => n + (r.usage[field] ?? 0), 0));
			assert.deepEqual(observation.totals.usage[field].unknownQuestions, observation.records.filter(r => r.usage[field] === null).map(r => r.id));
		}
		assert.ok(observation.records.every(r => r.scientificReview === "pending" && r.visuals.every(v => v.modelVisualInspection === "not_verifiable")));
		assert.equal(require("./fixtures/reading-quality/r0-v1-observation.json").scientificAnswerStatus, "not_run", "Keep the earlier observation unchanged");
	});
	console.log(`READING_QUALITY_RUNNER_OK: ${tests} groups; artifacts retained at ${root}`);
})().catch(error => { console.error(error); process.exitCode = 1; });
