const assert = require("node:assert/strict");
const path = require("node:path");
const { loadReading, memoryStorage } = require("./reading-test-helpers");
const { openCodeProject } = loadReading("code-reading/source.ts");
const { ReadingRepository, RoutedReadingStorage } = loadReading("reading/store.ts");
const { createReadingSession, addReadingNode, addReadingBranch, validateReadingSession } = loadReading("reading/session.ts");
const { ReadingEngine, validateReadingResult } = loadReading("reading/engine.ts");
const { readingExportContent } = loadReading("reading/export.ts");
const { readingDashboardState } = loadReading("reading/entry.ts");
(async () => {
	let code = Buffer.from("def add(a, b):\n    return a + b\n\nprint(add(1, 2))\n");
	const doc = await openCodeProject(path.resolve("project/main.py"), { stat: async () => ({ file: true, size: code.length }), realpath: async p => p, list: async () => [], read: async () => code });
	const regular = memoryStorage(), tests = memoryStorage(), codeStore = memoryStorage();
	const storage = new RoutedReadingStorage(regular, tests, codeStore); const repo = new ReadingRepository(storage);
	const session = createReadingSession(doc.source, "direct-test", "test"); const first = addReadingNode(session, null); await repo.add(session);
	assert(codeStore.files.has(session.id)); assert.equal(regular.files.size, 0);
	const evidenceId = doc.evidence[0].id; const requests = [];
	const backend = { name: "test", model: "test", images: false, async complete(request) {
		requests.push(request); assert.match(request.system, /代码|源码/); assert.doesNotMatch(request.system, /X-Ray|图表讲解必须/);
		const input = JSON.parse(request.prompt);
		if (input.action === "规划全文路线") return JSON.stringify({ modules: [{ title: "程序总览", question: "输入输出是什么", evidenceIds: [evidenceId] }, { title: "流程回顾", question: "怎么串起来", evidenceIds: [evidenceId] }] });
		if (request.system.includes("代码证据选择器")) return JSON.stringify({ ids: [evidenceId], query: "add", needsVisual: false });
		const main = !input.question;
		return JSON.stringify({ title: main ? input.currentUnit : "函数追问", content: (main ? input.currentUnit : input.question) + "：函数返回两个参数的和，未运行代码。[" + evidenceId + "]", evidenceIds: [evidenceId], ...(main ? { mainSummary: "已读 add 函数" } : {}) });
	} };
	const workspace = { repository: repo, document: async () => doc }; const engine = new ReadingEngine(workspace, () => backend);
	await Promise.all([engine.generate(session.id, first.id), engine.generate(session.id, first.id)]);
	assert.equal(requests.length, 3); assert.equal(repo.get(session.id).nodes[0].status, "done");
	const branchNode = await repo.transact(session.id, s => addReadingNode(s, addReadingBranch(s, first.id).id, "这里为什么有两个参数"));
	await engine.generate(session.id, branchNode.id); const snapshot = repo.get(session.id).branches[0].mainSnapshot;
	const next = await repo.transact(session.id, s => addReadingNode(s, null)); await engine.generate(session.id, next.id);
	assert(repo.get(session.id).completed); assert.equal(repo.get(session.id).branches[0].mainSnapshot, snapshot);
	assert.equal(readingDashboardState([repo.get(session.id)]).sessionId, "", "code never appears as PDF progress");
	assert.equal(readingDashboardState([repo.get(session.id)], "code").sessionId, session.id);
	const exportText = readingExportContent(repo.get(session.id), "session", first.id);
	assert.match(exportText, /static-read/); assert.match(exportText, /第 1–4 行/); assert.doesNotMatch(exportText, /X-Ray|\[\[.*main\.py/);
	const reloaded = new ReadingRepository(new RoutedReadingStorage(regular, tests, codeStore)); await reloaded.load();
	assert.equal(reloaded.get(session.id).nodes.length, 3); assert.equal(reloaded.errors.length, 0);
	const child = await repo.transact(session.id, s => addReadingNode(s, addReadingBranch(s, branchNode.id).id, "继续解释"));
	code = Buffer.from("def add(a, b):\n    return a - b\n"); const before = requests.length;
	await assert.rejects(engine.generate(session.id, child.id), /源码已变化/); assert.equal(requests.length, before, "changed source blocks before any model call");
	assert.equal(repo.get(session.id).nodes.at(-1).status, "failed"); assert.equal(repo.get(session.id).nodes[0].evidence[0].text, doc.evidence[0].text);
	const invalid = structuredClone(repo.get(session.id)); invalid.nodes[0].evidence[0].endLine = 99; assert.throws(() => validateReadingSession(invalid), /代码引用/);
	assert.throws(() => validateReadingResult(JSON.stringify({ title: "x", content: "[code-forged]", evidenceIds: [evidenceId] }), doc.evidence, false), /不一致/);
	const testSession = createReadingSession(doc.source); testSession.purpose = "test"; await repo.add(testSession); assert(tests.files.has(testSession.id));
	console.log("CODE_READING_SESSIONS_OK");
})().catch(error => { console.error(error); process.exitCode = 1; });
