"use strict";
// Synthetic buffers only. No network, credentials, filesystem writes or deletion.
const assert = require("node:assert/strict"), fs = require("node:fs");
const b = require("../scripts/reading-quality-baseline.cjs");
const actual = require("./fixtures/reading-quality/r0-v1.json");
assert.equal(actual.samples.length, 3); assert.ok(actual.samples.every(s => s.questions.length >= 6));
b.validateSpec(actual);
const observation = require("./fixtures/reading-quality/r0-v1-observation.json");
assert.equal(observation.baselineHash, b.sha(JSON.stringify(actual)), "Historical observation must name the frozen specification it inspected");
assert.equal(observation.questionCount, actual.samples.reduce((count, s) => count + s.questions.length, 0));
assert.equal(observation.scientificAnswerStatus, "not_run");
assert.equal(observation.independentReviewStatus, "pending");
assert.equal(observation.sourceChecks.find(s => s.id === "deseq2").jatsState, "blocked", "Keep original source failure when later implementations improve");
const id = "test", doi = "10.1234/test", title = "Example study";
const xml = Buffer.from(`<article><front><article-meta><article-id pub-id-type="doi">${doi}</article-id><article-id pub-id-type="pmcid">PMC123</article-id><title-group><article-title>${title}</article-title></title-group></article-meta></front><body><sec><title>Results</title><p id="p1">Measured value: 2 mg. Association is not causation.</p></sec></body></article>`);
const pdf = Buffer.from("%PDF-1.4\nSynthetic test only"), pageText = "Measured value: 2 mg. Association is not causation.";
const metadata = { title, doi, pmcid: "PMC123", version: 1, license_code: "CC BY", is_pmc_openaccess: true, is_retracted: false, is_manuscript: false };
const bytes = new Map([["article.xml", xml], ["source.pdf", pdf], ["metadata.json", Buffer.from(JSON.stringify(metadata))], ["pdf-text.json", Buffer.from(JSON.stringify({ extractor: "synthetic", sourceSha256: b.sha(pdf), pages: [{ page: 1, text: pageText }] }))]]);
const sample = { id, doi, title, pmcid: "PMC123", version: "PMC123.1", license: "CC-BY-4.0", files: [...bytes].map(([path, data]) => ({ path, sha256: b.sha(data), bytes: data.length })) };
const projection = b.projectSource(sample, bytes).projection, block = projection.blocks.find(v => v.xmlId === "p1");
sample.questions = [{ id: "Q1", category: "units", prompt: "What was measured?", primaryFormat: "jats", evidence: [{ format: "jats", blockId: block.id, xmlPath: block.xmlPath, sha256: b.sha(projection.markdown.slice(block.start, block.end)) }, { format: "pdf", page: 1, sha256: b.sha(pageText) }], visuals: [{ kind: "pdf-page", page: 1 }], expectedPoints: ["2 mg"], mustNotClaim: ["2 g"] }];
const spec = { schemaVersion: 1, id: "unit-test", referenceStatus: "provisional", samples: [sample] }, read = name => Buffer.from(bytes.get(name.split("/")[1]));
const before = JSON.stringify(spec), result = b.inspect(spec, read);
assert.equal(result.questionCount, 1); assert.equal(result.scientificAnswerStatus, "not_run"); assert.equal(result.independentReviewStatus, "pending");
assert.equal(result.modelInputs[0].visuals[0].delivery, "required_not_yet_provided");
assert.equal(result.modelInputs[0].expectedPoints, undefined); assert.equal(result.modelInputs[0].mustNotClaim, undefined);
assert.equal(result.sourceChecks[0].jatsState, "usable"); assert.equal(JSON.stringify(spec), before);
assert.deepEqual(result, b.inspect(spec, read));
assert.match(b.reviewMarkdown(spec, result), /待独立人工复核/);
const observed = b.observe(spec, read);
assert.equal(observed.historicalConverter, "rar-jats-2");
assert.equal(observed.currentSources[0].converter, "rar-jats-3");
assert.equal(observed.currentSources[0].anchors[0].state, "unchanged");
assert.equal(observed.scientificAnswerStatus, "not_run");
const changedBytes = new Map(bytes), changedSpec = structuredClone(spec);
changedBytes.set("article.xml", Buffer.from(xml.toString().replace("Measured value: 2 mg.", String.raw`Measured value: 2 mg. <inline-formula><tex-math>\documentclass{minimal}\begin{document}$x$\end{document}</tex-math></inline-formula>`)));
const changedFile = changedSpec.samples[0].files.find(f => f.path === "article.xml");
changedFile.bytes = changedBytes.get("article.xml").length; changedFile.sha256 = b.sha(changedBytes.get("article.xml"));
const historicalChanged = b.projectSource(changedSpec.samples[0], changedBytes).projection;
const changedBlock = historicalChanged.blocks.find(b => b.xmlId === "p1");
changedSpec.samples[0].questions[0].evidence[0] = { format: "jats", blockId: changedBlock.id, xmlPath: changedBlock.xmlPath, sha256: b.sha(historicalChanged.markdown.slice(changedBlock.start, changedBlock.end)) };
const beforeObservation = JSON.stringify(changedSpec);
assert.equal(b.observe(changedSpec, name => changedBytes.get(name.split("/")[1])).currentSources[0].anchors[0].state, "changed");
assert.equal(JSON.stringify(changedSpec), beforeObservation, "New converter must report changes without moving frozen anchors");
const bad = mutate => { const copy = structuredClone(spec); mutate(copy); return copy; };
for (const invalid of [bad(s => s.samples.push(s.samples[0])), bad(s => s.samples[0].questions.push(s.samples[0].questions[0])), bad(s => s.referenceStatus = "gold"), bad(s => s.samples[0].files[0].path = "../outside"), bad(s => s.samples[0].questions[0].evidence[0].format = "html")]) assert.throws(() => b.inspect(invalid, read));
assert.throws(() => b.inspect(spec, name => name.endsWith("article.xml") ? Buffer.from("changed") : read(name)), /hash mismatch/);
assert.throws(() => b.inspect(bad(s => s.samples[0].questions[0].evidence[0].blockId = "b-" + "0".repeat(24)), read), /anchor mismatch/);
assert.throws(() => b.inspect(bad(s => s.samples[0].questions[0].evidence[0].sha256 = "0".repeat(64)), read), /anchor mismatch/);
assert.throws(() => b.inspect(bad(s => s.samples[0].questions[0].evidence[1].page = 2), read), /anchor mismatch/);
assert.throws(() => b.inspect(bad(s => s.samples[0].questions[0].visuals[0].page = 2), read), /Visual page missing/);
const brokenBytes = new Map(bytes); brokenBytes.set("article.xml", Buffer.from("not XML"));
assert.equal(b.projectSource(sample, brokenBytes).state, "blocked");
assert.equal(b.projectSource(sample, brokenBytes).missingAssets, null, "Not inspected is not zero missing images");
// A known XML failure must stay blocked while an explicitly chosen PDF anchor can remain inspectable.
const broken = bad(s => { const f = s.samples[0].files.find(f => f.path === "article.xml"); f.bytes = 7; f.sha256 = b.sha("not XML"); s.samples[0].questions[0].primaryFormat = "pdf"; s.samples[0].questions[0].evidence.shift(); });
const blocked = b.inspect(broken, name => brokenBytes.get(name.split("/")[1]));
assert.equal(blocked.sourceChecks[0].jatsState, "blocked"); assert.equal(blocked.scientificAnswerStatus, "not_run");
assert.ok(blocked.modelInputs[0].evidence.every(e => e.format === "pdf"));
assert.ok(!/unlink|rmdir|rmSync/.test(fs.readFileSync(require.resolve("../scripts/reading-quality-baseline.cjs"), "utf8")));
console.log("READING_QUALITY_BASELINE_OK: pinned identities, bytes, pages, blocks, input/reference separation, explicit format, visible source failures, no automatic scientific approval");
