"use strict";
// Real services and committed topic events; memory-only, zero external requests or deletion.
const assert=require('node:assert/strict'),{loadReading}=require('./reading-test-helpers'),{mocks,TFile,readingFixture,topicFixture}=require('./answer-excerpt-fixtures.cjs');
const {readAnswerSnapshot,readingAnswerSnapshot,topicAnswerSnapshot}=loadReading('learning/answer-snapshot.ts',mocks);
const {prepareAnswerExcerpt,renderAnswerExcerpt,readAnswerExcerpt,AnswerExcerptService,answerExcerptText}=loadReading('learning/answer-excerpts.ts',mocks);
let count=0;async function test(name,run){await run();count++;console.log('PASS answer excerpts: '+name);}
(async()=>{
 await test('reading snapshot fixes model, source, evidence and correction metadata but ignores UI/self-rating',async()=>{const f=readingFixture(),a=f.answer();f.session.ui.zoom=1.2;f.node.learningState='understood';assert.equal(f.answer().digest,a.digest);f.node.model='changed';assert.notEqual(f.answer().digest,a.digest);f.node.status='failed';assert.throws(f.answer,/已完成/);f.node.status='done';f.session.purpose='test';assert.throws(f.answer,/正式/);f.session.purpose='reading';f.session.demo=true;assert.throws(f.answer,/正式/);});
 await test('topic request and route stay fixed through user understanding changes, without additional generation',async()=>{const f=await topicFixture(),s=await f.study(),a=topicAnswerSnapshot(s,s.nodes[0].id),writes=f.storage.writes.length;assert.equal((await readAnswerSnapshot(f.storage,a.ref)).digest,a.digest);assert.equal(f.storage.writes.length,writes);await f.service.mark(f.id,f.route,s.head,s.nodes[0].id,'understood');assert.equal((await readAnswerSnapshot(f.storage,a.ref)).digest,a.digest);assert.equal(f.calls(),1);const c=new AbortController();c.abort();await assert.rejects(readAnswerSnapshot(f.storage,a.ref,c.signal),/abort/i);});
 await test('source reads refuse duplicate sessions, missing nodes, mismatched IDs and pending topic commits',async()=>{const f=readingFixture(),a=f.answer();assert.equal((await readAnswerSnapshot(f.storage,a.ref)).digest,a.digest);assert.equal(f.storage.writes.length,0);f.storage.files.set('code-reading-sessions/'+f.session.id+'.json',f.storage.files.values().next().value);await assert.rejects(readAnswerSnapshot(f.storage,a.ref),/位置不一致|重复/);f.storage.files.clear();await assert.rejects(readAnswerSnapshot(f.storage,a.ref),/缺失/);await assert.rejects(readAnswerSnapshot(f.storage,{...a.ref,sessionId:'../escape'}),/标识/);const t=await topicFixture(),s=await t.study(),b=topicAnswerSnapshot(s,s.nodes[0].id);t.storage.files.set('topic-learning-dialogues/'+t.id+'/'+t.route+'/e-00000000-0000-0000-0000-000000000000.json',Buffer.from('{}'));await assert.rejects(readAnswerSnapshot(t.storage,b.ref),/不完整/);});
 await test('exact Markdown slice, Unicode and literal fences preserve roles without executable content',async()=>{const f=readingFixture(),a=f.answer(),start=a.content.lastIndexOf('重复句'),r=prepareAnswerExcerpt(a,start,start+3,'User note\n```\n[[link]]');const result=await f.service.save(r),text=f.files.get(result.file.path).text;assert.equal(answerExcerptText(result.file.record),'重复句');assert.match(text,/type: learning-answer-excerpt/);assert.match(text,/evidence_basis: ai-answer/);assert.equal(readAnswerExcerpt(text,result.file.path).record.note,r.note);const full=renderAnswerExcerpt(prepareAnswerExcerpt(a));assert.ok(full.includes('````text\n'+a.content+'\n````'));assert.throws(()=>prepareAnswerExcerpt(a,a.content.indexOf('😀')+1,a.content.length),/字符/);assert.throws(()=>prepareAnswerExcerpt(a,2,2),/非空/);assert.equal(f.storage.writes.length,0);});
 await test('repeat/concurrent saves and service reload reuse exact excerpt while preserving edited personal notes',async()=>{const f=readingFixture(),r=prepareAnswerExcerpt(f.answer(),0,5,'initial'),other=new AnswerExcerptService(f.app,(ref,s)=>readAnswerSnapshot(f.storage,ref,s));const results=await Promise.all([f.service.save(r),other.save(r)]);assert.equal(f.writes.length,1);const saved=await other.saveNote(results[0].file,'my edited note'),again=await f.service.save(r);assert.equal(again.reused,true);assert.equal(again.file.record.note,'my edited note');assert.deepEqual(saved.record.answer,r.answer);assert.equal((await other.list()).entries.length,1);});
 await test('version changes before save or during directory creation refuse writes; post-commit change reports history warning',async()=>{const f=readingFixture(),r=prepareAnswerExcerpt(f.answer());f.node.content+=' changed';f.persist();await assert.rejects(f.service.save(r),/版本/);assert.equal(f.writes.length,0);const g=readingFixture(),r2=prepareAnswerExcerpt(g.answer()),folder=g.app.vault.createFolder;g.app.vault.createFolder=async p=>{await folder(p);g.node.content+=' later';g.persist();};await assert.rejects(g.service.save(r2),/版本/);assert.equal(g.writes.length,0);const h=readingFixture(),create=h.app.vault.create;h.app.vault.create=async(...args)=>{const f=await create(...args);h.node.content+=' after commit';h.persist();return f;};const out=await h.service.save(prepareAnswerExcerpt(h.answer()));assert.match(out.warning,/已保存/);assert.equal((await h.service.load(out.file.path)).record.answer.content.includes('after commit'),false);});
 await test('cancel, disk failure, lost response and corrupt occupied file never overwrite',async()=>{const f=readingFixture(),r=prepareAnswerExcerpt(f.answer()),c=new AbortController();c.abort();await assert.rejects(f.service.save(r,c.signal),/abort/i);assert.equal(f.writes.length,0);const create=f.app.vault.create;f.app.vault.create=async()=>{throw Error('disk unavailable');};await assert.rejects(f.service.save(r),/disk unavailable/);f.app.vault.create=async(...args)=>{await create(...args);throw Error('response lost');};const out=await f.service.save(r);assert.equal(out.reused,true);f.files.get(out.file.path).text='User content';await assert.rejects(f.service.save(r),/凭据/);assert.equal(f.files.get(out.file.path).text,'User content');});
 await test('memo edits compare the entire file and file identity; historical answers remain editable',async()=>{const f=readingFixture(),out=await f.service.save(prepareAnswerExcerpt(f.answer())),file=f.files.get(out.file.path);file.text+='User appendix';const altered=file.text;await assert.rejects(f.service.saveNote(out.file,'draft'),/修改/);assert.equal(file.text,altered);file.text=renderAnswerExcerpt(out.file.record);f.storage.files.clear();assert.equal((await f.service.saveNote(out.file,'historical note')).record.note,'historical note');const latest=await f.service.load(out.file.path),process=f.app.vault.process;f.app.vault.process=async(file,fn)=>{f.files.get(file.path).file=new TFile(file.path);return process(file,fn);};await assert.rejects(f.service.saveNote(latest,'moved'),/修改/);});
 await test('corrupt snapshots, payload, visible text and path mismatches are refused with read issues',async()=>{const f=readingFixture(),out=await f.service.save(prepareAnswerExcerpt(f.answer())),text=f.files.get(out.file.path).text;for(const bad of [text.replace('## AI 回答片段','## Forged'),text+text,text.replace('"version":1','"version":2')])assert.throws(()=>readAnswerExcerpt(bad,out.file.path));assert.throws(()=>readAnswerExcerpt(text,'wiki/sources/forged.md'),/路径/);f.files.get(out.file.path).text='corrupt';const list=await f.service.list();assert.equal(list.entries.length,0);assert.equal(list.issues.length,1);});
 await test('answer excerpts stay outside lexical, learning, formal and curation evidence scopes',async()=>{const p='wiki/qa/answer-excerpts/answer-'+'a'.repeat(48)+'.md',files=[new TFile(p),new TFile('wiki/qa/moved.md'),new TFile('wiki/concepts/moved.md'),new TFile('wiki/qa/old.md')],read=[];const app={vault:{getMarkdownFiles:()=>files,cachedRead:async f=>{read.push(f.path);return '# General\nGeneral answer';}},metadataCache:{getFileCache:f=>({frontmatter:f.path.includes('moved')?{type:'learning-answer-excerpt'}:{}})}};const {LexicalVaultRetriever}=loadReading('query/lexical-retrieval.ts',mocks);await new LexicalVaultRetriever(app).retrieve('General');assert.deepEqual([...new Set(read)],['wiki/qa/old.md']);read.length=0;const {LearningLibrary}=loadReading('curation/learning.ts',mocks),lib=new LearningLibrary(app,{ready:async()=>{},repository:{sessions:new Map()}},{read:async()=>null,write:async()=>{}},{},()=> 'lexical');assert.deepEqual((await lib.documents()).map(d=>d.path),['wiki/qa/old.md']);lib.dispose();assert.deepEqual(await loadReading('retrieval/vault.ts',mocks).readKnowledgeDocuments(app),[]);assert.equal(loadReading('retrieval/chunks.ts').inKnowledgeScope(p),false);assert.equal(loadReading('curation/policy.ts').curationTarget(p),false);});
 await test('topic save/reload retains route and request receipts without writing study history',async()=>{
  const t=await topicFixture(),s=await t.study(),answer=topicAnswerSnapshot(s,s.nodes[0].id),vault=readingFixture(),writes=t.storage.writes.length;
  const service=new AnswerExcerptService(vault.app,(ref,signal)=>readAnswerSnapshot(t.storage,ref,signal));
  const saved=await service.save(prepareAnswerExcerpt(answer,0,answer.content.length,'Topic memo'));
  const reloaded=new AnswerExcerptService(vault.app,(ref,signal)=>readAnswerSnapshot(t.storage,ref,signal));
  assert.deepEqual((await reloaded.load(saved.file.path)).record.answer,answer);await reloaded.verify(answer);
  assert.equal(t.storage.writes.length,writes);assert.equal(t.calls(),1);assert.match(vault.files.get(saved.file.path).text,/模型一般知识/);
 });
 await test('static code explanation saves with exact source and quote context without executing project code',async()=>{
  const path=require('node:path'),{openCodeProject}=loadReading('code-reading/source.ts');
  const doc=await openCodeProject(path.resolve('project/main.py'),{stat:async()=>({file:true,size:27}),realpath:async p=>p,list:async()=>[],read:async()=>Buffer.from('def add(a,b): return a + b\n')});
  const f=readingFixture();f.session.source=doc.source;f.node.evidence=doc.evidence;
  f.storage.files.clear();f.storage.files.set('code-reading-sessions/'+f.session.id+'.json',Buffer.from(JSON.stringify(f.session)));
  const answer=f.answer(),saved=await f.service.save(prepareAnswerExcerpt(answer));assert.equal(answer.context.kind,'code');
  assert.equal((await f.service.load(saved.file.path)).record.answer.context.digest,answer.context.digest);
  assert.match(f.files.get(saved.file.path).text,/未据此执行代码/);assert.equal(f.storage.writes.length,0);
 });
 console.log(`ANSWER_EXCERPTS_OK (${count} groups; memory-only)`);
})().catch(error=>{console.error(error);process.exitCode=1;});
