const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { createReadingSession, addReadingNode } = loadReading("reading/session.ts");
const { readingExportContent } = loadReading("reading/export.ts");
const { curationNodeOutcomes, exportedNodes, readReadingOutcomes } = loadReading("reading/outcomes.ts");
(async () => {
	const s = createReadingSession({ kind: "pdf", path: "a.pdf", fingerprint: "a".repeat(64), title: "paper" });
	const n = addReadingNode(s, null); n.status = "done"; n.content = "Answer";
	const text = readingExportContent(s, "node", n.id); assert.deepEqual(exportedNodes(text, s), [{ id: n.id, label: "已导出" }]);
	n.learningState = "question"; n.usage = []; assert.equal(exportedNodes(text, s)[0].label, "已导出");
	n.content += " changed"; assert.equal(exportedNodes(text, s)[0].label, "已导出旧版");
	assert.equal(exportedNodes(text.replace(/,"hash":"[a-f0-9]+"/, ""), s)[0].label, "已导出（旧记录）");
	assert.deepEqual(exportedNodes("---\nreading_nodes: malformed\n---\n", s), []);
	assert.deepEqual(exportedNodes(text, { ...s, id: "another" }), []);
	const review = { id: "c-1", context: { sessionId: s.id, nodeIds: [n.id], target: { path: "wiki/sources/a.md" } }, state: "ready", suggestions: [{ decision: "pending" }] };
	const labels = revisions => curationNodeOutcomes(s.id, n.id, [review], revisions).map(r => r.label);
	assert.deepEqual(labels([]), ["待审阅"]); assert.deepEqual(curationNodeOutcomes(s.id, "other", [review], []), []);
	const applied = { id: "write", reviewId: review.id, state: "applied" }; review.suggestions[0].decision = "applied";
	assert.deepEqual(labels([applied]), ["已采纳"]);
	assert.deepEqual(labels([{ ...applied, needsReview: "changed" }]), ["需复查"]);
	assert.deepEqual(labels([{ ...applied, state: "recovery" }]), ["待恢复"]);
	assert.deepEqual(labels([applied, { id: "undo", reviewId: review.id, state: "applied", undoOf: applied.id }]), ["已撤销"]);
	assert.deepEqual(labels([applied, { id: "undo", reviewId: review.id, state: "recovery", undoOf: applied.id }]), ["已采纳", "待恢复"]);
	review.state = "stale"; assert.deepEqual(labels([]), ["需复查"]);
	const file = { path: "wiki/qa/test.md" }; let reads = 0;
	const app = { vault: { getMarkdownFiles: () => [file, { path: "papers/raw.md" }], cachedRead: async () => { reads++; return text; } }, metadataCache: { getFileCache: () => null } };
	const service = { ready: async () => {}, reviews: new Map([[review.id, review]]), revisions: new Map() };
	const map = await readReadingOutcomes(app, s, service); assert.equal(reads, 1); assert.deepEqual(map.get(n.id).map(r => r.label), ["需复查", "已导出旧版"]);
	assert.equal(map.get(n.id)[0].reviewId, review.id); assert.equal(map.get(n.id)[1].path, file.path);
	console.log("READING_OUTCOMES_OK");
})().catch(e => { console.error(e); process.exitCode = 1; });
