const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { readingDashboardState } = loadReading("reading/entry.ts");
const { createReadingSession, addReadingNode, addReadingBranch } = loadReading("reading/session.ts");
const create = title => createReadingSession({ kind: "pdf", path: title + ".pdf", fingerprint: "a".repeat(64), title });
const old = create("Old"), recent = create("Recent"), demo = create("Demo");
old.lastOpenedAt = "2026-01-01"; recent.lastOpenedAt = "2026-02-01"; demo.demo = true;
assert.equal(readingDashboardState([demo]).sessionId, "");
assert.equal(readingDashboardState([old, recent]).sessionId, recent.id);
old.outline = ["A", "B"]; const main = addReadingNode(old, null);
assert.equal(readingDashboardState([old, recent]).sessionId, old.id);
main.status = "done"; main.title = "A";
const branch = addReadingBranch(old, main.id); const follow = addReadingNode(old, branch.id, "Question");
assert.equal(readingDashboardState([old, recent]).running, true);
assert.match(readingDashboardState([old]).label, /1\/2 单元/);
follow.status = "interrupted";
assert.match(readingDashboardState([old]).label, /待重试/);
old.archived = true; assert.equal(readingDashboardState([old]).sessionId, "");
console.log("READING_ENTRY_OK");
