"use strict";
// Mock providers and in-memory objects only; no file writes or cleanup.
const assert = require("node:assert/strict");
const { loadReading } = require("./reading-test-helpers");
const { OpenAIProvider, OpenAICompatibleProvider } = loadReading("providers/adapters.ts");
const { normalizeProviderProfile } = loadReading("providers/profile.ts");
const { structuredProfileKey, supportsReadingSchema } = loadReading("providers/structured.ts");
const { probeReadingSchema } = loadReading("assistant/probe.ts");
const { DirectReadingBackend, readingUsage } = loadReading("reading/backend.ts");
const { ASSISTANT_SCHEMA } = loadReading("assistant/capabilities.ts");
const { READING_MEMORY_SCHEMA, READING_SELECTION_SCHEMA, readingAnswerSchema, CURATION_SCHEMA } = loadReading("reading/schemas.ts");
(async () => {
	const p = normalizeProviderProfile({ id: "p", type: "openai-compatible", baseUrl: "https://example.test/v1", model: "m", secretId: "test" });
	let captured;
	const host = { app: { secretStorage: { getSecret: () => "test-placeholder" } }, providerHttpRequest: async request => { captured = request; return { json: { choices: [{ message: { content: "{}" } }] } }; }, providerHttpStream: async request => { captured = request; request.onEvent(JSON.stringify({ type: "response.output_text.delta", delta: "{}" })); } };
	const chat = new OpenAICompatibleProvider(host, p);
	const request = { messages: [{ role: "user", content: "JSON" }], responseSchema: { name: "reading", schema: ASSISTANT_SCHEMA } };
	await chat.complete(request); assert.deepEqual(captured.body.response_format, { type: "json_schema", json_schema: { ...request.responseSchema, strict: true } }); assert.equal(captured.body.enable_search, undefined);
	await chat.complete({ messages: request.messages }); assert.equal(captured.body.response_format, undefined);
	const openai = new OpenAIProvider(host, { ...p, type: "openai" });
	await openai.complete(request); assert.deepEqual(captured.body.text.format, { type: "json_schema", strict: true, ...request.responseSchema });
	await openai.stream(request, () => {}); assert.deepEqual(captured.body.text.format, { type: "json_schema", strict: true, ...request.responseSchema });
	assert.equal(supportsReadingSchema(p), false);
	const goodProbe = await probeReadingSchema({ complete: async r => {
		const answer = r.responseSchema.schema.properties.step.anyOf.find(s => s.properties.tool.enum[0] === "final").properties.arguments.properties.answer.enum[0];
		assert.ok(!JSON.stringify(r.messages).includes(answer));
		return { text: JSON.stringify({ step: { tool: "final", arguments: { answer, citations: [] } } }), raw: { usage: { prompt_tokens: 100, completion_tokens: 30 } } };
	} }, p);
	assert.equal(goodProbe.verified, true); assert.equal(goodProbe.input, 100);
	const verified = normalizeProviderProfile({ ...p, structuredOutput: goodProbe }); assert.equal(supportsReadingSchema(verified), true);
	for (const field of ["model", "baseUrl", "secretId", "type"]) assert.equal(supportsReadingSchema({ ...verified, [field]: "changed" }), false);
	assert.equal(structuredProfileKey(p), goodProbe.key);
	const ignored = await probeReadingSchema({ complete: async () => ({ text: JSON.stringify({ step: { tool: "final", arguments: { answer: "plain", citations: [] } } }) }) }, p); assert.equal(ignored.verified, false);
	const unsupported = await probeReadingSchema({ complete: async () => { throw new Error("400 unsupported schema"); } }, p); assert.equal(unsupported.verified, false); assert.match(unsupported.message, /本地/);
	const skipped = await probeReadingSchema({ complete: () => { throw new Error("must not call"); } }, { ...p, type: "anthropic" }); assert.equal(skipped.verified, false);
	const fake = { capabilities: { vision: false }, complete: async r => { captured = r; return { text: "{}", raw: { usage: { input_tokens: 200, output_tokens: 30, input_tokens_details: { cached_tokens: 100 } } } }; } };
	const input = { system: "rules", prompt: "query", images: [], signal: new AbortController().signal, schema: ASSISTANT_SCHEMA };
	await new DirectReadingBackend(fake, "n", "m", false).complete(input); assert.equal(captured.responseSchema, undefined);
	let usage; await new DirectReadingBackend(fake, "n", "m", false, true).complete({ ...input, onUsage: u => usage = u }); assert.deepEqual(captured.responseSchema.schema, ASSISTANT_SCHEMA); assert.equal(usage.cachedInput, 100);
	assert.equal(readingUsage({ prompt_tokens: 0, completion_tokens: 0 }).input, 0); assert.equal(readingUsage({}), undefined);
	const check = schema => { if (schema.type === "object") { assert.equal(schema.additionalProperties, false); assert.deepEqual([...schema.required].sort(), Object.keys(schema.properties).sort()); Object.values(schema.properties).forEach(check); } if (schema.items) check(schema.items); if (schema.anyOf) schema.anyOf.forEach(check); };
	for (const schema of [ASSISTANT_SCHEMA, READING_MEMORY_SCHEMA, READING_SELECTION_SCHEMA, readingAnswerSchema(true), readingAnswerSchema(false), CURATION_SCHEMA]) check(schema);
	assert.ok(readingAnswerSchema(true).required.includes("outline")); assert.ok(!readingAnswerSchema(false).required.includes("outline"));
	console.log("READING_SCHEMA_OK: native protocols, unverified fallback, probe challenge, profile invalidation, usage, shared schemas");
})().catch(e => { console.error(e); process.exitCode = 1; });
