const assert=require("node:assert/strict"),{loadReading}=require("./reading-test-helpers"),{fixture}=require("./jats-fixtures.cjs");
const {parseXml}=loadReading("jats/xml.ts"),{projectJats}=loadReading("jats/projection.ts"),f=fixture(),image={ref:"fig1.png",path:"images/"+"a".repeat(64)+".png"};
const p=projectJats(f.xml,f.identity,[image]);assert.equal(p.identifiers.doi,f.identity.identifiers.doi);assert.ok(!Object.values(p.identifiers).includes("10.9999/reference"));assert.equal(p.authors[0],"Test Author");assert.equal(p.blocks.filter(b=>b.kind==="table").length,2);assert.ok(p.blocks.find(b=>b.xmlId==="t2").table[0][0].colspan===2);assert.ok(p.markdown.includes("$x^2$"));assert.ok(p.markdown.includes("# Methods"));assert.equal(p.bodyCheck,"usable");assert.equal(p.projectionId,projectJats(f.xml,f.identity,[image]).projectionId);assert.ok(p.references.every(r=>p.blocks.some(b=>b.id===r.target)));
for(const b of p.blocks){assert.ok(b.start<b.end&&b.end<=p.markdown.length);assert.ok(f.xml.toString().slice(b.sourceStart,b.sourceEnd).startsWith("<"));}
for(const malicious of ['<!DOCTYPE article [<!ENTITY x SYSTEM "file:///secret">]><article>&x;</article>','<!DOCTYPE article [<!ENTITY a "123"><!ENTITY b "&a;&a;">]><article>&b;</article>','<article>&unknown;</article>','<article a="1" a="2"/>','<article><body></article>','<article/> <article/>','<article>'+"<sec>".repeat(100)+"</sec>".repeat(100)+"</article>"]){assert.throws(()=>parseXml(Buffer.from(malicious)));}
const referenceOnly=f.xml.toString().replace(`<article-id pub-id-type="doi">${f.identity.identifiers.doi}</article-id>`,"").replace('<article-id pub-id-type="pmc">123</article-id>',"").replace(new RegExp('<article-id pub-id-type="pmid">[^<]+</article-id>'),"");assert.throws(()=>projectJats(Buffer.from(referenceOnly),f.identity,[]),/精确标识/);
const math=f.xml.toString().replace('<tex-math>x^2</tex-math>','<mml:math><mml:mfrac><mml:mi>x</mml:mi><mml:mn>2</mml:mn></mml:mfrac></mml:math>');assert.ok(projectJats(Buffer.from(math),f.identity,[image]).issues.some(s=>s.includes("MathML")));
const hostile=f.xml.toString().replace('Example abstract.','&lt;script&gt;alert(1)&lt;/script&gt; [[secret]] ![remote](https://example.org/x) <script>bad()</script>');const safe=projectJats(Buffer.from(hostile),f.identity,[image]);assert.ok(!safe.markdown.includes("<script>"));assert.ok(!safe.markdown.includes("[[secret]]"));assert.ok(!safe.markdown.includes("![remote](https"));assert.ok(safe.issues.length);
assert.ok(projectJats(f.xml,f.identity,[]).issues.some(s=>s.includes("图片")));console.log("JATS_PROJECTION_OK: bounded XML, no entities, main-article identity, deterministic blocks/maps, captions, lists, tables, formulas, references and passive text");
const {validateJatsProjection}=loadReading("jats/validation.ts");
assert.equal(validateJatsProjection({includeFigures:false,issues:[]},projectJats(f.xml,f.identity,[])).requestSatisfaction,"satisfied");
assert.equal(validateJatsProjection({includeFigures:true,issues:[]},projectJats(Buffer.from(math),f.identity,[image])).requestSatisfaction,"partial");
const nested=f.xml.toString().replace('Input &amp; output','10<sup>2</sup> H<sub>2</sub>O Input &amp; output').replace('</p><list>','<fig id="nested"><label>NestedFigure</label><caption><p>OnlyOnce</p></caption></fig></p><list>');
const np=projectJats(Buffer.from(nested),f.identity,[image]);assert.equal(np.markdown.match(/OnlyOnce/g).length,1);assert.ok(np.markdown.includes("10^(2) H_(2)O"));
const injection=f.xml.toString().replace('x^2','<![CDATA[x $ ![remote](https://example.org/x) $]]>');const ip=projectJats(Buffer.from(injection),f.identity,[image]);assert.ok(ip.issues.some(s=>s.includes("公式")));assert.ok(!ip.markdown.includes("![remote](https"));
const graphical=f.xml.toString().replace('Example abstract.','Example abstract.<boxed-text><graphic xlink:href="fig1.png"/></boxed-text>');const gp=projectJats(Buffer.from(graphical),f.identity,[image]);assert.equal(gp.blocks.filter(b=>b.kind==="figure").length,2,"graphical abstracts retain standalone mapped image blocks");
